"""Application-owned ports. Domain/application never depend on vendor or SQL types."""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, ContextManager, Any, Callable
from eija_studio.domain.formal import FormalArtifact
from eija_studio.domain.models import Proposal, Workflow
from eija_studio.domain.pack import Pack
from eija_studio.domain.transactions import Transaction

@dataclass(frozen=True)
class ProviderResult:
    proposal: Proposal
    provider: str
    model: str
    usage: dict[str, Any]
    live: bool

class ProposalProvider(Protocol):
    name: str
    networked: bool
    def propose(self, request: str, model: Workflow) -> ProviderResult: ...
    def doctor(self) -> dict[str, Any]: ...

class EditProposer(Protocol):
    """Offline request resolution only; returns an untrusted transaction and performs no IO or persistence."""
    def propose(self, request: str, model: Workflow, choices: tuple[Transaction, ...]) -> dict[str, Any]: ...

class PlanProposer(Protocol):
    """Turns a chat request into {summary, meaning, steps: [{transaction, why}]}. Untrusted; no IO or persistence.
    With `grows`, the system is one the person started, so a step may name a state, action or role it lacks (ADR-0201)."""
    name: str
    live: bool
    def propose(self, request: str, model: Workflow, pack: Pack, *, grows: bool = False) -> dict[str, Any]: ...
    def follow_on(self, ripple: dict[str, Any], model: Workflow, pack: Pack) -> dict[str, Any]:
        """Follow-on steps for a ripple's problems (ADR-0158): {steps: [{transaction | screen, why, fixes}]}."""
        ...

class UnitOfWork(Protocol):
    """All mutations on this port commit together or roll back together."""
    def load_case(self, case_id: str) -> dict[str, Any]: ...
    def save_case(self, case: dict[str, Any], expected: int) -> None: ...
    def insert_case(self, case: dict[str, Any]) -> None: ...
    def active(self) -> dict[str, Any]: ...
    def set_active(self, model: Workflow, expected: int) -> None: ...
    def event(self, kind: str, body: dict[str, Any]) -> None: ...
    def actor(self, actor_id: str) -> dict[str, Any]: ...
    def create_instance(self, item: dict[str, Any]) -> None: ...
    def find_instance(self, instance_id: str, case_id: str) -> dict[str, Any] | None: ...
    def update_instance(self, item: dict[str, Any], expected: int) -> None: ...
    def find_operation(self, operation_id: str) -> dict[str, Any] | None: ...
    def record_operation(self, operation_id: str, binding: str, result: dict[str, Any]) -> None: ...
    def enqueue(self, case_id: str, operation_id: str, effect: str, recipient: str) -> None: ...
    def observations(self, case_id: str) -> dict[str, Any]: ...
    def effect_counts(self) -> dict[str, Any]: ...

class FormalEvidenceSource(Protocol):
    """Where formal artifacts come from (Docker, Java, z3 or saved reports are adapter prerequisites).

    A missing prerequisite is returned as a NOT_RUN artifact, never omitted and never a pass."""
    def collect(self, baseline: Workflow, candidate: Workflow) -> list[FormalArtifact]: ...


class Repository(Protocol):
    directory: Path
    def transaction(self) -> ContextManager[UnitOfWork]: ...
    def list_cases(self) -> list[dict[str, Any]]: ...
    def backup(self, target: Path) -> None: ...

class ReceiptAuthenticator(Protocol):
    def seal(self, value: dict[str, Any]) -> dict[str, Any]: ...
    def authentic(self, value: dict[str, Any]) -> bool: ...

IdentityProvider = Callable[[], dict[str, Any]]
# Opens a disposable verification sandbox. It need not be durable but must keep UnitOfWork atomicity,
# and it is deleted when the context exits.
SandboxFactory = Callable[[], ContextManager[Repository]]
