"""Application-owned ports. Domain/application never depend on vendor or SQL types."""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, ContextManager, Any, Callable
from eija_studio.domain.models import Proposal, Workflow

@dataclass(frozen=True)
class ProviderResult:
    proposal: Proposal
    provider: str
    model: str
    usage: dict[str, Any]
    live: bool

class ProposalProvider(Protocol):
    name: str
    networked: bool
    def propose(self, request: str, model: Workflow) -> ProviderResult: ...
    def doctor(self) -> dict: ...

class UnitOfWork(Protocol):
    """All mutations on this port commit together or roll back together."""
    def load_case(self, case_id: str) -> dict: ...
    def save_case(self, case: dict, expected: int) -> None: ...
    def insert_case(self, case: dict) -> None: ...
    def active(self) -> dict: ...
    def set_active(self, model: Workflow, expected: int) -> None: ...
    def event(self, kind: str, body: dict) -> None: ...
    def actor(self, actor_id: str) -> dict: ...
    def create_instance(self, item: dict) -> None: ...
    def find_instance(self, instance_id: str, case_id: str) -> dict | None: ...
    def update_instance(self, item: dict, expected: int) -> None: ...
    def find_operation(self, operation_id: str) -> dict | None: ...
    def record_operation(self, operation_id: str, binding: str, result: dict) -> None: ...
    def enqueue(self, case_id: str, operation_id: str, effect: str) -> None: ...
    def observations(self, case_id: str) -> dict: ...
    def effect_counts(self) -> dict: ...

class Repository(Protocol):
    directory: Path
    def transaction(self) -> ContextManager[UnitOfWork]: ...
    def list_cases(self) -> list[dict]: ...
    def backup(self, target: Path) -> None: ...

class ReceiptAuthenticator(Protocol):
    def seal(self, value: dict) -> dict: ...
    def authentic(self, value: dict) -> bool: ...

IdentityProvider = Callable[[], dict]
# Opens a disposable verification sandbox. It need not be durable but must keep UnitOfWork atomicity,
# and it is deleted when the context exits.
SandboxFactory = Callable[[], ContextManager[Repository]]
