"""Generate the TLC model modules and configurations from the executable Python workflow.

    python -m verification.tla.generate            # rewrite generated/ (LF, deterministic)
    python -m verification.tla.generate --check    # drift check: exit 1 if committed files differ

Output is a pure function of the kernel's workflow, actor directory and the bounds in `model.py`:
sorted where order is not semantic, no timestamps, no host paths. If the kernel's transition table
changes, `--check` fails until the model is regenerated, so the specification cannot silently drift
from the code's data. It does not check `Decide` (the decision procedure): conformance does.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any

from .model import (INVARIANTS, MUTABLE_ACTORS, PROPERTIES, UNKNOWN_ACTORS, TlaConfig, action_universe,
                    configs, directory, forbidden_effects, op_ids, transition_table)

HERE = Path(__file__).resolve().parent
OUT = HERE / "generated"
HEADER = "\\* GENERATED by verification/tla/generate.py from the executable Python workflow. DO NOT EDIT.\n"


class Rec(dict):
    """Rendered as a TLA+ record: [field |-> value, ...]."""


def tla(value: Any) -> str:
    """Render a Python value as a TLA+ expression (deterministic)."""
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        if '"' in value or "\\" in value:
            raise ValueError("unsupported character in TLA+ string")
        return f'"{value}"'
    if isinstance(value, (tuple, list)):
        return "<< " + ", ".join(tla(v) for v in value) + " >>" if value else "<<>>"
    if isinstance(value, Rec):
        return "[" + ", ".join(f"{k} |-> {tla(v)}" for k, v in value.items()) + "]"
    if isinstance(value, dict):  # function with string domain (keys may contain '-')
        if not value:
            raise ValueError("empty function is not representable")
        return " @@ ".join(f"({tla(k)} :> {tla(v)})" for k, v in value.items())
    if isinstance(value, (set, frozenset)):
        return "{" + ", ".join(tla(v) for v in sorted(value)) + "}"
    raise TypeError(f"cannot render {type(value)!r}")


def constants(config: TlaConfig, ops: int) -> dict[str, str]:
    """The value of every constant of Excursion.tla for one configuration."""
    actors = directory()
    return {
        "OpSeq": tla(op_ids(ops)),
        "ActorSeq": tla(tuple(a[0] for a in actors)),
        "UnknownSeq": tla(UNKNOWN_ACTORS),
        "MutableSeq": tla(MUTABLE_ACTORS),
        "ActionSeq": tla(action_universe()),
        "States": tla(set(config.workflow.states)),
        "InitialState": tla(config.workflow.initial_state),
        "ActorRole": tla({a[0]: a[1] for a in actors}),
        "InitDir": tla({a[0]: Rec(active=bool(a[2]), assigned=bool(a[3])) for a in actors}),
        "Table": tla({k: Rec(v) for k, v in transition_table(config.workflow).items()}),
        "Forbidden": tla(set(forbidden_effects(config.workflow))),
        "MaxVer": str(ops),
        "Mutation": tla(config.mutation),
    }


def module_text(config: TlaConfig, *, dump: bool) -> str:
    ops = config.dump_ops if dump else config.check_ops
    name = module_name(config, dump)
    lines = [f"---- MODULE {name} ----", HEADER.rstrip("\n"),
             f"\\* workflow semantic_hash: {config.workflow.semantic_hash}",
             f"\\* {config.description}", f"\\* protected-policy verdict on this workflow: {list(config.policy_errors) or 'accepted'}",
             "EXTENDS Excursion", ""]
    lines += [f"MC_{key} == {value}" for key, value in constants(config, ops).items()]
    lines += ["", "===="]
    return "\n".join(lines) + "\n"


def cfg_text(config: TlaConfig, *, dump: bool) -> str:
    name = module_name(config, dump)
    lines = ["\\* GENERATED by verification/tla/generate.py. DO NOT EDIT.", "SPECIFICATION Spec", "CONSTANTS"]
    lines += [f"    {key} <- MC_{key}" for key in constants(config, 1)]
    if dump:
        lines += ["INVARIANT", "    Emit"]
    else:
        lines += ["INVARIANTS"] + [f"    {i}" for i in INVARIANTS]
        lines += ["PROPERTIES"] + [f"    {p}" for p in PROPERTIES]
    lines += ["CHECK_DEADLOCK", "    FALSE", ""]
    del name
    return "\n".join(lines)


def trace_files(config: TlaConfig, ops: int, traces: list[dict[str, Any]], *, mutation: str | None = None,
                label: str | None = None) -> dict[str, str]:
    """Trace-validation module + cfg for observed runtime traces (run-time artefacts, not committed)."""
    name = f"MCT_{label or config.name}"
    values = constants(config, ops)
    if mutation is not None:
        values["Mutation"] = tla(mutation)
    nl = chr(10)
    literal = tla(tuple((t["init"], tuple(t["steps"])) for t in traces))
    module = nl.join([f"---- MODULE {name} ----", HEADER.rstrip(nl), "EXTENDS ExcursionTrace", ""]
                     + [f"MC_{k} == {v}" for k, v in values.items()] + [f"MC_Traces == {literal}", "", "===="]) + nl
    cfg = nl.join(["SPECIFICATION TSpec", "CONSTANTS"] + [f"    {k} <- MC_{k}" for k in [*values, "Traces"]]
                  + ["INVARIANT", "    TNoDivergence", "CHECK_DEADLOCK", "    FALSE", ""])
    return {f"{name}.tla": module, f"{name}.cfg": cfg}


def dump_files(config: TlaConfig, *, mutation: str, label: str) -> dict[str, str]:
    """A dump module for a seeded-defect variant of `config` (sensitivity control; not committed)."""
    seeded = replace(config, mutation=mutation, name=label)
    return {f"MCD_{label}.tla": module_text(seeded, dump=True), f"MCD_{label}.cfg": cfg_text(seeded, dump=True)}


def module_name(config: TlaConfig, dump: bool) -> str:
    return ("MCD_" if dump else "MC_") + config.name


def generated_files() -> dict[str, str]:
    """relative path -> content, for every committed generated file."""
    files: dict[str, str] = {}
    for config in configs():
        variants = [False] if config.negative_control else [False, True]
        for dump in variants:
            name = module_name(config, dump)
            files[f"{name}.tla"] = module_text(config, dump=dump)
            files[f"{name}.cfg"] = cfg_text(config, dump=dump)
    return files


def write_files(files: dict[str, str]) -> None:
    OUT.mkdir(exist_ok=True)
    for stale in OUT.glob("MC*"):
        if stale.name not in files:
            stale.unlink()
    for name, text in files.items():
        (OUT / name).write_bytes(text.encode("utf-8"))


def drift(files: dict[str, str] | None = None) -> list[str]:
    """Human-readable differences between committed generated files and a fresh generation."""
    files = files if files is not None else generated_files()
    problems = []
    for name, text in files.items():
        path = OUT / name
        if not path.exists():
            problems.append(f"missing: {name}")
        elif path.read_bytes() != text.encode("utf-8"):
            problems.append(f"differs: {name}")
    problems += [f"stale: {p.name}" for p in sorted(OUT.glob("MC*")) if p.name not in files]
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if committed generated files differ")
    args = parser.parse_args(argv)
    files = generated_files()
    if args.check:
        problems = drift(files)
        for p in problems:
            print("TLA+ model drift:", p)
        print("tla drift check:", "FAIL" if problems else f"ok ({len(files)} generated files match the kernel)")
        return 1 if problems else 0
    write_files(files)
    print(f"wrote {len(files)} files to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
