"use strict";
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => {const x=document.createElement(tag); if(text!==undefined)x.textContent=text; if(cls)x.className=cls; return x;};
let token = location.hash.slice(1) || sessionStorage.getItem("eija-session") || "";
if(location.hash){sessionStorage.setItem("eija-session",token); history.replaceState(null,"",location.pathname);}
let current=null, instance=null, status=null, tab="change", busy=false, editId=null;
// The transition the typed edit retargets: the last one whose source the candidate moved (else the first). Pack-agnostic.
function editTarget(c){const before=new Map(c.baseline.transitions.map(t=>[t.id,t.from_state]));const moved=c.candidate.transitions.filter(t=>before.has(t.id)&&before.get(t.id)!==t.from_state);return moved.length?moved[moved.length-1]:c.candidate.transitions[0];}
function fillStates(id,states,value){$(id).replaceChildren(...states.map(s=>el("option",s)));$(id).value=value;}
const notice=(text,error=false)=>{$("notice").textContent=text;$("notice").className=error?"error":"";};
async function api(path,body){const options={headers:{Authorization:"Bearer "+token}};if(body!==undefined){options.method="POST";options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);}const r=await fetch("/api/"+path,options);const data=await r.json();if(!r.ok)throw new Error((data.code||r.status)+": "+(data.message||"Request failed"));return data;}
async function task(fn,message="Working…"){if(busy)return;busy=true;notice(message);document.body.setAttribute("aria-busy","true");try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;document.body.removeAttribute("aria-busy");}}
async function cases(){const data=await api("cases");$("case-list").replaceChildren();for(const c of data){const b=el("button",c.request.slice(0,80),current?.case.id===c.id?"selected":"");b.append(el("small",c.stage));b.onclick=()=>task(async()=>{instance=null;await load(c.id);notice("");});$("case-list").append(b);}}
function switchTab(name){tab=name;if(name==="visual")loadVisual();document.querySelectorAll(".tab-content").forEach(x=>x.hidden=x.id!==name);document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));}
function formalList(parent,title,items){if(!items||!items.length)return;parent.append(el("h4",title));const ul=el("ul");for(const x of items)ul.append(el("li",typeof x==="string"?x:JSON.stringify(x)));parent.append(ul);}
function explanation(root,x,lead){const box=el("div",undefined,"formal-explain");box.append(el("strong",lead+x.control+" ("+(x.source||"")+")"));box.append(el("p",(x.trace?"Counterexample trace: "+x.trace.map(s=>s.join(" ")).join(" -> ")+(x.final_state?" ends "+x.final_state:""):"Witness: "+JSON.stringify(x.witness))+". "+(x.note||"")));root.append(box);}
function renderFormal(p){const root=$("formal");root.replaceChildren();for(const m of p.blocked_meanings||[]){root.append(el("p","Blocked meaning: "+m.label+" ("+(m.policy_errors||[]).join(", ")+")","formal-blocked"));for(const x of m.explanations||[])explanation(root,x,"Why the policy refuses it: ");}
for(const x of p.explanations||[])explanation(root,x,"Why the policy blocks this: ");
for(const e of p.formal_evidence||[]){const d=el("details",undefined,"formal-item status-"+e.status.toLowerCase());d.append(el("summary",e.kind.replaceAll("_"," ")+": "+e.status+" ("+e.evidence_level.replaceAll("_"," ")+")"));d.append(el("p",e.establishes));formalList(d,"Why this status",e.reasons);formalList(d,"Does not establish",e.does_not_establish);formalList(d,"Assumptions",e.assumptions);if(e.bounds)formalList(d,"Bounds",[JSON.stringify(e.bounds)]);formalList(d,"Counterexamples",e.counterexamples);d.append(el("small","Needs: "+e.prerequisites));root.append(d);}}
async function load(id){current=await api("cases/"+id);render();await cases();}
async function command(action,extra={}){const id=current.case.id;const result=await api(`cases/${id}/${action}`,{expected_version:current.case.version,...extra});await load(id);return result;}
function render(){const c=current.case,p=current.packet,closed=["APPLIED","DISCARDED"].includes(c.stage);$("create-panel").hidden=true;$("workspace").hidden=false;$("case-title").textContent=c.request;$("case-id").textContent=`CHANGE CASE ${c.id.slice(0,10)} / REVISION ${c.version} / BASELINE ${c.baseline_version}`;$("case-stage").textContent=c.stage;$("proposal-summary").textContent=c.proposal?.summary||"No interpretation has been requested. Your request is not yet a semantic change.";$("propose").disabled=!!c.candidate||closed;$("options").replaceChildren();
for(const a of c.proposal?.alternatives||[]){const canonical=current.options[a.interpretation],chosen=c.selected_meaning===a.interpretation;const card=el("article",undefined,"option"+(chosen?" selected":""));card.append(el("small",chosen?"SELECTED BY LOCAL OWNER":canonical.supported?"SUPPORTED MEANING":"BLOCKED / OUT OF SCOPE"),el("h3",canonical.label));for(const consequence of canonical.consequences)card.append(el("p",consequence));const d=el("details");d.append(el("summary","Untrusted provider explanation"),el("p",a.explanation));card.append(d);const b=el("button",chosen?"Meaning selected":canonical.supported?"Select this meaning":"Explain boundary",chosen?"secondary":"");b.disabled=closed||!!c.candidate;b.onclick=()=>task(async()=>{await command("select",{interpretation:a.interpretation});notice("Meaning selected. The local baseline has not changed.");});card.append(b);$("options").append(card);}
$("proposal-unknowns").replaceChildren();for(const unknown of c.proposal?.unknowns||[])$("proposal-unknowns").append(el("p","Unresolved: "+unknown,"muted"));$("editor").hidden=!c.candidate;
for(const id of ["save","discard","edit-rule","edit-state","move-node","verify","reset"])$(id).disabled=!c.candidate||closed;
if(c.candidate){const target=editTarget(c);editId=target.id;$("rejection-label").textContent=`${target.action} may start from`;$("diagram-label").textContent=`State-view edit: ${target.action} starts at`;fillStates("rejection-source",c.candidate.states,target.from_state);fillStates("diagram-source",c.candidate.states,target.from_state);$("rule-table").replaceChildren();for(const t of p.projections.rules){const row=el("tr");[t.action,t.role,t.from_state,t.to_state,t.guards.includes("actor_assigned")?"Active + assigned":"Active + current role"].forEach(v=>row.append(el("td",v)));$("rule-table").append(row);}$("state-flow").replaceChildren();$("layout-node").replaceChildren();for(const s of p.projections.states){const node=el("div",undefined,"state-node");node.append(el("strong",s.id));for(const a of s.next_actions)node.append(el("small",`${a.role}: ${a.action} → ${a.target}`));if(!s.next_actions.length)node.append(el("small","Terminal state"));if(c.layout[s.id])node.append(el("small",`Saved layout: ${c.layout[s.id].x}, ${c.layout[s.id].y}`));$("state-flow").append(node);const option=el("option",s.id);$("layout-node").append(option);}$("impact-summary").textContent=`${p.impact.changed_actions.length} changed actions · ${p.impact.affected.length} modelled dependants · closure ${p.impact.complete?"complete within this mapping":"INCOMPLETE"}`;$("impact-json").textContent=JSON.stringify({impact:p.impact,subject:p.subject},null,2);$("journeys").replaceChildren(...p.projections.journeys.map(j=>el("p",j,"muted")));}else{for(const id of ["rule-table","state-flow","layout-node","journeys"])$(id).replaceChildren();$("impact-summary").textContent="Select a supported meaning before viewing a candidate.";$("impact-json").textContent="";}
$("runtime-actions").replaceChildren();for(const action of status?.pack?.actions||[]){const b=el("button",action,"secondary");b.disabled=!instance||closed;b.onclick=()=>task(async()=>{const result=await api(`cases/${c.id}/execute`,{operation_id:crypto.randomUUID(),actor_id:$("actor").value,instance_id:instance.id,action,expected_version:instance.version});instance=result.instance;await load(c.id);$("runtime-result").textContent="Committed: "+action+". Effects: "+result.effects.join(", ");notice("Commit completed; the displayed state is persisted.");});$("runtime-actions").append(b);}$("runtime-state").textContent=instance?.state||"Not started";$("runtime-version").textContent=instance?`Instance ${instance.id.slice(0,8)} · version ${instance.version} · isolated candidate`:"No candidate state has been executed";$("trace").textContent=JSON.stringify(current.observations,null,2);
$("claims").replaceChildren();for(const [name,value]of Object.entries(p.technical_claims||{})){const card=el("div",undefined,"evidence-card");card.append(el("span",name.replaceAll("_"," ")),el("strong",value));$("claims").append(card);}renderFormal(p);$("blockers").textContent=p.blockers?.length?"Review blocked: "+p.blockers.join(", "):"Technical scope eligible. Human authorisation is still a separate decision.";$("packet").textContent=JSON.stringify(p,null,2);$("questions").replaceChildren();for(const q of p.questions||[]){const div=el("div",undefined,"question"),label=el("label",q.question);label.htmlFor="q-"+q.id;const input=el("input");input.id="q-"+q.id;input.name=q.id;input.autocomplete="off";input.required=true;div.append(label,input);$("questions").append(div);}$("approve").disabled=!p.eligible||closed||c.stage==="APPROVED";$("apply").disabled=c.stage!=="APPROVED"||!p.eligible;$("export").disabled=false;switchTab(tab);}
$("create").onclick=()=>task(async()=>{const c=await api("cases",{request:$("request").value});instance=null;tab="change";await load(c.id);notice("Case created. No provider call or baseline change has occurred.");});$("new-case").onclick=()=>{$("workspace").hidden=true;$("create-panel").hidden=false;notice("");};document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$("propose").onclick=()=>task(async()=>{await command("propose",{consent:$("egress").checked});notice("Interpretations received. No meaning was selected automatically.");},"Requesting an untrusted proposal…");
$("save").onclick=()=>task(async()=>{await command("save");notice("Review checkpoint saved; the active baseline is unchanged.");});$("discard").onclick=()=>task(async()=>{await command("discard");instance=null;render();notice("Candidate closed. History is retained; the baseline is unchanged.");});
function edit(source){return task(async()=>{await command("edit",{transaction:{kind:"retarget_transition",transition:editId,end:"source",state:source}});instance=null;render();notice("Candidate changed. Old evidence remains immutable and is now inapplicable; re-run verification.");});}$("edit-rule").onclick=()=>edit($("rejection-source").value);$("edit-state").onclick=()=>edit($("diagram-source").value);
$("move-node").onclick=()=>task(async()=>{await command("layout",{change:{node:$("layout-node").value,x:Number($("layout-x").value),y:Number($("layout-y").value)}});notice("Layout metadata changed. Domain receipts remain applicable; exact-presentation approval is cleared.");});
$("reset").onclick=()=>task(async()=>{instance=await command("preview");render();$("runtime-result").textContent="";notice(`Fresh isolated instance created in ${instance.state}.`);});
$("verify").onclick=()=>task(async()=>{await command("verify");notice("Bounded runtime verification finished. Human evidence remains UNKNOWN.");},"Executing the synthetic state / actor / action matrix…");
$("review-form").onsubmit=e=>{e.preventDefault();task(async()=>{const answers={};for(const q of current.packet.questions)answers[q.id]=$("q-"+q.id).value.trim();await command("approve",{subject_hash:current.packet.subject_hash,answers,acknowledge_unknowns:$("acknowledge").checked,scope:"local-demo"});notice("Exact local revision acknowledged. Apply remains a separate action.");});};
$("apply").onclick=()=>task(async()=>{await command("apply");status=await api("status");notice("Applied to the local demo baseline only. No production system was touched.");});
$("export").onclick=()=>task(async()=>{const data=await api(`cases/${current.case.id}/export`),blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=el("a");a.href=url;a.download=`eija-${current.case.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice("Case exported with model, evidence, observations and integrity hash.");});
$("doctor").onclick=()=>task(async()=>{notice(JSON.stringify(await api("doctor")));});
function showPack(pack){if(!pack)return;$("pack-name").textContent=pack.name;if(!$("request").value)$("request").value=pack.demo_request;$("actor").replaceChildren(...pack.actors.map(a=>{const o=el("option",`${a.role} · ${a.assigned?"assigned":"unassigned"} / ${a.active?"active":"revoked"}`);o.value=a.id;return o;}));}
task(async()=>{status=await api("status");showPack(status.pack);$("connection").textContent=`${status.provider} · ${status.network_enabled?"network enabled":"local / offline"}`;await cases();notice(status.trusted_fixture?"":"SOURCE REVIEW REQUIRED: implementation differs from the release fixture",!status.trusted_fixture);});
// Visual view: diagram text is generated server-side from the executable model and drawn inside a sandboxed frame
// (see visual-frame.js and docs/SECURITY_AND_TRUST.md). This page never parses or inserts diagram markup itself.
let visual={data:null,ready:false,seq:0};
function diffItems(s){const at=x=>Array.isArray(x)?x.join(", ")||"none":String(x),out=[];if(!s)return out;if(s.initial_state)out.push(`Start state: ${s.initial_state.before} → ${s.initial_state.after}`);
for(const [label,list] of [["Added states",s.added_states],["Removed states",s.removed_states],["Added actions",s.added_actions],["Removed actions",s.removed_actions]])if(list.length)out.push(`${label}: ${list.join(", ")}`);
for(const [action,changes] of Object.entries(s.changed_actions))out.push(`Changed ${action}: `+changes.map(c=>`${c.field} ${at(c.before)} → ${at(c.after)}`).join("; "));
return out.length?out:["No semantic change between baseline and candidate."];}
function visualPanels(){const v=visual.data.views,d=visual.data,action=$("visual-action").value,list=[{id:"before",title:"Before (baseline)",note:"The active rules.",text:v.state_before,group:"row"}];
if(v.state_after){list.push({id:"after",title:"After (candidate)",note:"The rules if this candidate were applied.",text:v.state_after,group:"row"},{id:"diff",title:"Diff",note:"Nodes: green added, red removed (dashed outline), amber changed. Edges cannot be coloured in a state diagram, so a label starting + - or ~ marks an added, removed or changed transition and a ~ label names what changed; the list below repeats it as text.",text:v.diff,items:diffItems(d.summary),group:"row"},{id:"impact",title:"Ripple: what this change touches",note:d.impact.envelope,text:v.impact});}
if(v.sequences[action])list.push({id:"sequence",title:"Commit protocol: "+action,note:"Order of checks and writes in one atomic commit.",text:v.sequences[action]});
list.push({id:"journey",title:"Journeys by role",note:"Only transitions each role may perform.",text:v.journey});if(v.class)list.push({id:"class",title:"Domain contracts",note:"Introspected from the typed contracts.",text:v.class});return list;}
function postVisual(){const frame=$("visual-frame");if(!visual.ready||!visual.data||!frame.contentWindow)return;frame.contentWindow.postMessage({type:"eija.visual.render",panels:visualPanels()},"*");}
window.addEventListener("message",e=>{const frame=$("visual-frame");if(e.source!==frame.contentWindow)return;const m=e.data||{};if(m.type==="eija.visual.ready"){visual.ready=true;postVisual();}else if(m.type==="eija.visual.size"&&Number.isFinite(m.height))frame.style.height=Math.min(Math.max(m.height,240),16000)+"px";});
$("visual-action").onchange=postVisual;
async function loadVisual(){if(!current)return;const id=current.case.id,mine=++visual.seq,frame=$("visual-frame");if(!frame.getAttribute("src"))frame.setAttribute("src","/visual-frame");
try{const data=await api(`cases/${id}/diagrams`);if(mine!==visual.seq)return;visual.data=data;const select=$("visual-action"),previous=select.value,actions=Object.keys(data.views.sequences);select.replaceChildren(...actions.map(x=>el("option",x)));
const added=actions.find(x=>!current.case.baseline.transitions.some(t=>t.action===x));select.value=actions.includes(previous)?previous:added||actions[0]||"";
const subject=current.packet.subject?.semantic,candidate=data.sources.candidate;
$("visual-source").textContent=`Generated from workflow hash ${data.sources.baseline.slice(0,12)} (baseline)`+(candidate?` and ${candidate.slice(0,12)} (candidate) · ${candidate===subject?"matches the evidence subject":"DOES NOT MATCH the evidence subject"}`:" · no candidate yet: select a meaning to see the diff and ripple")+(data.policy_violations&&data.policy_violations.length?" · POLICY BLOCKED: "+data.policy_violations.join("; "):"");
postVisual();}catch(e){notice(e.message,true);}}
