"use strict";
// Renders diagram text sent by the Studio page. Runs in a sandboxed frame (opaque origin, no API access,
// no token): it can only draw what the parent posts. The text is generated by the server from the
// executable model and rendered by the vendored Mermaid in `securityLevel: strict`.
const panels = document.getElementById("panels");
const MAX_PANELS = 12, MAX_TEXT = 200000, MAX_ITEMS = 60;
let generation = 0;
const send = message => parent.postMessage(message, "*");  // opaque origin: the target can only be addressed as "*"
const el = (tag, text, cls) => { const x = document.createElement(tag); if (text !== undefined) x.textContent = text; if (cls) x.className = cls; return x; };
if (typeof mermaid !== "undefined") mermaid.initialize({ startOnLoad: false, securityLevel: "strict", htmlLabels: true, theme: "default" });

async function panel(spec) {
  const section = el("section"), figure = el("figure"), pre = el("pre", spec.text, "mermaid");
  section.id = "panel-" + spec.id;
  section.append(el("h3", spec.title));
  if (spec.note) section.append(el("p", spec.note, "note"));
  figure.append(pre); section.append(figure);
  if (spec.items.length) { const list = el("ul", undefined, "changes"); for (const item of spec.items) list.append(el("li", item)); section.append(list); }
  return { section, pre };
}

async function draw(list) {
  const mine = ++generation;
  panels.replaceChildren();
  const built = [];
  let grid = null;
  for (const spec of list) {
    const p = await panel(spec);
    if (spec.group === "row") {
      if (!grid) { grid = el("div", undefined, "group"); panels.append(grid); }
      grid.append(p.section);
    } else { panels.append(p.section); }
    built.push(p);
  }
  for (const p of built) {
    if (mine !== generation) return;
    if (typeof mermaid === "undefined") { p.section.prepend(el("p", "Renderer unavailable; showing generated text.", "error")); continue; }
    try { await mermaid.run({ nodes: [p.pre], suppressErrors: false }); }
    catch (e) { p.section.prepend(el("p", "Could not render: " + String((e && e.message) || e).slice(0, 200), "error")); }
  }
  report();
}

function report() { send({ type: "eija.visual.size", height: Math.ceil(document.documentElement.scrollHeight) }); }
new ResizeObserver(report).observe(document.body);

window.addEventListener("message", event => {
  if (event.source !== parent) return;
  const data = event.data;
  if (!data || data.type !== "eija.visual.render" || !Array.isArray(data.panels)) return;
  const list = data.panels.slice(0, MAX_PANELS).filter(p => p && typeof p.id === "string" && typeof p.title === "string"
    && typeof p.text === "string" && p.text.length <= MAX_TEXT).map(p => ({ id: p.id.replace(/[^A-Za-z0-9_-]/g, "_"), title: p.title.slice(0, 120),
    note: typeof p.note === "string" ? p.note.slice(0, 400) : "", text: p.text,
    items: Array.isArray(p.items) ? p.items.filter(i => typeof i === "string").slice(0, MAX_ITEMS).map(i => i.slice(0, 300)) : [], group: p.group === "row" ? "row" : "" }));
  draw(list);
});
send({ type: "eija.visual.ready" });
