"""WBS 1.5: the vocabulary fitness gate (quality/gates/vocabulary.py).

Proof: the real tree has no pack token outside packs/, GENERATED files and the justified allowlist, and no
``Literal[...]`` naming a pack token anywhere scanned. Negative controls: a planted pack token in generic code fails the
gate; a planted ``Literal`` fails it even inside an allowlisted file; each exclusion excludes only what it says.
"""
from __future__ import annotations

import json
from pathlib import Path

from quality.gates import vocabulary as V

ROOT = Path(__file__).resolve().parents[2]
PACK = {"pack": {"id": "orchard"}, "model": {"id": "orchard", "states": ["Blossom", "Harvested"], "transitions": [
    {"id": "TR-PICK", "action": "Pick", "role": "Picker", "from_state": "Blossom", "to_state": "Harvested"}]},
        "roles": [{"id": "Picker"}], "actions": [{"id": "Pick", "required_effects": ["Audit:FruitPicked"]}],
        "effects": {"catalog": [{"id": "Audit:FruitPicked"}], "forbidden": ["FruitSold"]}, "meanings": [{"id": "pick_early"}],
        "laws": [{"id": "picker-only"}], "fixtures": {"actors": [{"id": "picker-1"}]}}


def _tree(tmp_path: Path, files: dict[str, str]) -> Path:
    (tmp_path / "packs" / "orchard").mkdir(parents=True)
    (tmp_path / "packs" / "orchard" / "pack.json").write_text(json.dumps(PACK), encoding="utf-8")
    for rel, text in files.items():
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return tmp_path


def test_the_real_tree_passes_the_gate():
    findings = V.scan(ROOT)
    assert findings == [], [f.render() for f in findings[:20]]


def test_tokens_come_from_every_pack_including_bare_effect_names():
    tokens = V.pack_tokens(ROOT / "packs")
    assert {"excursion", "library-loan"} <= set(tokens)
    assert {"PaymentCaptured", "Librarian", "OnLoan", "LoanCheckedOut", "Audit:LoanCheckedOut"} <= set(tokens)
    assert V.COMMON_WORDS.isdisjoint(tokens)


def test_a_planted_pack_token_in_generic_code_fails(tmp_path):
    root = _tree(tmp_path, {"src/app/policy.py": 'if t.role == "Picker":\n    pass\n', "src/app/ok.py": "picking = 1\n"})
    found = V.scan(root)
    assert [(f.path, f.line, f.token, f.kind) for f in found] == [("src/app/policy.py", 1, "Picker", "word")]


def test_a_planted_literal_fails_even_in_an_allowlisted_file(tmp_path, monkeypatch):
    monkeypatch.setitem(V.ALLOWLIST, "src/app/debt.py", "test debt")
    root = _tree(tmp_path, {"src/app/debt.py": 'from typing import Literal\nKind = Literal["Blossom", "x"]\nnote = "Blossom"\n'})
    assert [(f.token, f.kind) for f in V.scan(root)] == [("Blossom", "literal")]


def test_a_namespaced_effect_in_a_literal_is_caught_by_its_bare_name(tmp_path):
    root = _tree(tmp_path, {"src/app/fx.py": 'from typing import Literal\nFx = Literal["Notify:FruitSold"]\n'})
    assert {(f.token, f.kind) for f in V.scan(root)} == {("Notify:FruitSold", "literal"), ("FruitSold", "word")}


def test_exclusions_exclude_only_what_they_say(tmp_path):
    root = _tree(tmp_path, {
        "src/app/generated.py": "# GENERATED by a tool; do not edit\nx = 'Harvested'\n",
        "src/app/marked.py": "x = 'Harvested'  # vocab-ok: test\ny = 'Harvested'\n",
        "docs/free.md": "Harvested\n",  # outside the scanned roots
    })
    assert [(f.path, f.line) for f in V.scan(root)] == [("src/app/marked.py", 2)]


def test_main_exits_nonzero_on_a_finding_and_zero_on_the_real_tree(tmp_path, capsys):
    root = _tree(tmp_path, {"scripts/x.py": "who = 'picker-1'\n"})
    assert V.main(["--root", str(root)]) == 1
    assert "scripts/x.py:1: word 'picker-1'" in capsys.readouterr().out
    assert V.main([]) == 0
