"""WBS 1.5: the vocabulary fitness gate (quality/gates/vocabulary.py).

Proof: the real tree has no pack token outside packs/, GENERATED files and the justified allowlist, and no
``Literal[...]`` naming a pack token anywhere scanned. Negative controls: a planted pack token in generic code fails the
gate; a planted ``Literal`` fails it even inside an allowlisted file; each exclusion excludes only what it says.
"""
from __future__ import annotations

import json

import pytest
from pathlib import Path

from quality.gates import vocabulary as V

ROOT = Path(__file__).resolve().parents[2]
PACK = {"pack": {"id": "orchard"}, "model": {"id": "orchard", "states": ["Blossom", "Harvested"], "transitions": [
    {"id": "TR-PICK", "action": "Pick", "role": "Picker", "from_state": "Blossom", "to_state": "Harvested"}]},
        "roles": [{"id": "Picker"}], "actions": [{"id": "Pick", "required_effects": ["Audit:FruitPicked"]}],
        "effects": {"catalog": [{"id": "Audit:FruitPicked"}], "forbidden": ["FruitSold"]}, "meanings": [{"id": "pick_early"}],
        "laws": [{"id": "picker-only"}], "fixtures": {"actors": [{"id": "picker-1"}]}}


def _tree(tmp_path: Path, files: dict[str, str]) -> Path:
    (tmp_path / "packs" / "orchard").mkdir(parents=True)
    (tmp_path / "packs" / "orchard" / "pack.json").write_text(json.dumps(PACK), encoding="utf-8")
    for rel, text in files.items():
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return tmp_path


def test_the_real_tree_passes_the_gate():
    findings = V.scan(ROOT)
    assert findings == [], [f.render() for f in findings[:20]]


def test_tokens_come_from_every_pack_including_bare_effect_names():
    tokens = V.pack_tokens(ROOT / "packs")
    assert {"excursion", "library-loan"} <= set(tokens)
    assert {"PaymentCaptured", "Librarian", "OnLoan", "LoanCheckedOut", "Audit:LoanCheckedOut"} <= set(tokens)
    assert V.COMMON_WORDS.isdisjoint(tokens)


def test_a_planted_pack_token_in_generic_code_fails(tmp_path):
    root = _tree(tmp_path, {"src/app/policy.py": 'if t.role == "Picker":\n    pass\n', "src/app/ok.py": "picking = 1\n"})
    found = V.scan(root)
    assert [(f.path, f.line, f.token, f.kind) for f in found] == [("src/app/policy.py", 1, "Picker", "word")]


def test_a_planted_literal_fails_even_in_an_allowlisted_file(tmp_path, monkeypatch):
    monkeypatch.setitem(V.ALLOWLIST, "src/app/debt.py", "test debt")
    root = _tree(tmp_path, {"src/app/debt.py": 'from typing import Literal\nKind = Literal["Blossom", "x"]\nnote = "Blossom"\n'})
    assert [(f.token, f.kind) for f in V.scan(root)] == [("Blossom", "literal")]


def test_a_namespaced_effect_in_a_literal_is_caught_by_its_bare_name(tmp_path):
    root = _tree(tmp_path, {"src/app/fx.py": 'from typing import Literal\nFx = Literal["Notify:FruitSold"]\n'})
    assert {(f.token, f.kind) for f in V.scan(root)} == {("Notify:FruitSold", "literal"), ("FruitSold", "word")}


def test_exclusions_exclude_only_what_they_say(tmp_path):
    root = _tree(tmp_path, {
        "src/app/generated.py": "# GENERATED by a tool; do not edit\nx = 'Harvested'\n",
        "src/app/marked.py": "x = 'Harvested'  # vocab-ok: test\ny = 'Harvested'\n",
        "docs/free.md": "Harvested\n",  # outside the scanned roots
    })
    assert [(f.path, f.line) for f in V.scan(root)] == [("src/app/marked.py", 2)]


def test_main_exits_nonzero_on_a_finding_and_zero_on_the_real_tree(tmp_path, capsys):
    root = _tree(tmp_path, {"scripts/x.py": "who = 'picker-1'\n"})
    assert V.main(["--root", str(root)]) == 1
    assert "scripts/x.py:1: word 'picker-1'" in capsys.readouterr().out
    assert V.main([]) == 0


# Kernel vocabulary is source-owned only through a reviewed export and an exact pack binding.
# These fixtures intentionally use foreign domain words as the exports to prove provenance handling.

def _bind_orchard(root: Path, binding: str) -> None:
    path = root / "packs/orchard/pack.json"
    doc = json.loads(path.read_text(encoding="utf-8"))
    doc["language"] = {"terms": [{"binds": [binding]}]}
    path.write_text(json.dumps(doc), encoding="utf-8")


def test_bound_kernel_enum_is_grounded_without_exempting_other_domain_tokens(tmp_path, monkeypatch):
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"src/app/contracts.py#Review": "stage_enum"})
    root = _tree(tmp_path, {
        "src/app/contracts.py": 'from typing import Literal\nclass Review:\n    stage: Literal["Blossom"]\n',
        "src/app/policy.py": 'stage = "Blossom"\nrole = "Picker"\n',
    })
    _bind_orchard(root, "repo://src/app/contracts.py#Review")
    assert [(finding.path, finding.token) for finding in V.scan(root)] == [("src/app/policy.py", "Picker")]


def test_a_self_binding_never_exempts_another_packs_shared_token(tmp_path, monkeypatch):
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"src/app/contracts.py#Review": "stage_enum"})
    root = _tree(tmp_path, {
        "src/app/contracts.py": 'from typing import Literal\nclass Review:\n    stage: Literal["Blossom"]\n',
    })
    _bind_orchard(root, "repo://src/app/contracts.py#Review")
    foreign = root / "packs/foreign/pack.json"
    foreign.parent.mkdir()
    foreign.write_text(json.dumps(PACK), encoding="utf-8")
    assert V.pack_tokens(root / "packs")["Blossom"] == {"foreign"}
    assert {(finding.token, finding.kind) for finding in V.scan(root)} == {
        ("Blossom", "literal"), ("Blossom", "word"),
    }


@pytest.mark.parametrize("source,binding", [
    ('class Renamed:\n    stage = "Blossom"\n', "repo://src/app/contracts.py#Review"),
    ('invalid syntax!', "repo://src/app/contracts.py#Review"),
    ('class Review:\n    note = "Blossom"\n', "repo://src/app/contracts.py#Review"),
    ('class Review:\n    stage = "Blossom"\n', "repo://src/app/contracts.py#Missing"),
])
def test_unproven_or_stale_exports_cannot_exempt_a_planted_token(tmp_path, monkeypatch, source, binding):
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"src/app/contracts.py#Review": "stage_enum"})
    root = _tree(tmp_path, {"src/app/contracts.py": source, "src/app/policy.py": 'stage = "Blossom"\n'})
    _bind_orchard(root, binding)
    assert any((finding.path, finding.token) == ("src/app/policy.py", "Blossom") for finding in V.scan(root))


def test_method_labels_require_an_exact_reviewed_source_binding(tmp_path, monkeypatch):
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"src/app/service.py#Review": "method_labels"})
    root = _tree(tmp_path, {
        "src/app/service.py": 'class Review:\n    def pick(self):\n        note = "Picker"\n',
        "src/app/use.py": 'action = "Pick"\n',
    })
    _bind_orchard(root, "repo://src/app/service.py#Review.pick")
    assert [(finding.token, finding.path) for finding in V.scan(root)] == [("Picker", "src/app/service.py")]
    _bind_orchard(root, "repo://src/app/service.py#Review")
    assert any(finding.token in {"Pick"} for finding in V.scan(root))


def test_missing_source_and_forged_export_path_fail_closed(tmp_path, monkeypatch):
    root = _tree(tmp_path, {"src/app/policy.py": 'stage = "Blossom"\n'})
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"src/missing.py#Review": "stage_enum"})
    _bind_orchard(root, "repo://src/missing.py#Review")
    assert "Blossom" in V.pack_tokens(root / "packs")
    monkeypatch.setattr(V, "KERNEL_EXPORTS", {"../outside.py#Review": "stage_enum"})
    assert V.kernel_exports(root) == {}
