"""Generate and check the ADR index in docs/adr/README.md.

Lanes add ADR *files*; nobody edits the index table by hand, so parallel lanes cannot conflict on it.
The generated table lives between two marker comments; everything else in the README (the reserved
number blocks) stays hand-written.

    python -m quality.tools.adr_index --write     # regenerate
    python -m quality.tools.adr_index --check     # fail on drift, duplicate numbers or unparsable ADRs
"""
# ruff: noqa: T201
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
START = "<!-- adr-index:start (generated by `python -m quality.tools.adr_index --write`; do not edit) -->"
END = "<!-- adr-index:end -->"
_FILE = re.compile(r"^(\d{4})-.+\.md$")
_TITLE = re.compile(r"^#\s+(?:HCI-)?ADR-(\d{4}):\s*(.+?)\s*$")
_STATUS = re.compile(r"^\*\s+Status:\s*(.+?)\s*$")


@dataclass(frozen=True)
class Adr:
    number: str
    file: str
    title: str
    status: str


def parse_adr(path: Path) -> tuple[Adr | None, str | None]:
    """Return (adr, problem). A record must start with `# ADR-NNNN: title` and carry `* Status:`."""
    match = _FILE.match(path.name)
    if not match:
        return None, None
    number, title, status = match.group(1), None, None
    for line in path.read_text(encoding="utf-8").splitlines()[:20]:
        if title is None and (t := _TITLE.match(line)):
            if t.group(1) != number:
                return None, f"{path.name}: heading says ADR-{t.group(1)} but the file is numbered {number}"
            title = t.group(2)
        if status is None and (s := _STATUS.match(line)):
            status = re.split(r"\s*\(", s.group(1), maxsplit=1)[0].strip()
    if title is None:
        return None, f"{path.name}: no '# ADR-{number}: <title>' heading in the first 20 lines"
    if status is None:
        return None, f"{path.name}: no '* Status: ...' line in the first 20 lines"
    return Adr(number, path.name, title, status), None


def collect(adr_dir: Path) -> tuple[list[Adr], list[str]]:
    adrs: list[Adr] = []
    problems: list[str] = []
    for path in sorted(adr_dir.glob("[0-9][0-9][0-9][0-9]-*.md")):
        adr, problem = parse_adr(path)
        if problem:
            problems.append(problem)
        elif adr:
            adrs.append(adr)
    seen: dict[str, str] = {}
    for adr in adrs:
        if adr.number in seen:
            problems.append(f"duplicate ADR number {adr.number}: {seen[adr.number]} and {adr.file}")
        seen[adr.number] = adr.file
    return adrs, problems


def render_table(adrs: list[Adr]) -> str:
    rows = ["| ADR | Decision | Status |", "|---|---|---|"]
    for adr in sorted(adrs, key=lambda a: a.number):
        # computed outside the f-string: Python 3.11 forbids backslashes inside f-string expressions
        title = adr.title.replace("|", "\\|")
        rows.append(f"| [{adr.number}]({adr.file}) | {title} | {adr.status} |")
    return "\n".join(rows)


_BLOCK = re.compile(r"<!-- adr-index:start[^>]*-->.*?<!-- adr-index:end -->", re.DOTALL)


def render_readme(readme: str, adrs: list[Adr]) -> str:
    """Replace whatever sits between the markers with the generated table (markers are normalised)."""
    block = f"{START}\n{render_table(adrs)}\n{END}"
    if not _BLOCK.search(readme):
        raise ValueError("docs/adr/README.md has no adr-index markers; add them where the table should go")
    return _BLOCK.sub(lambda _: block, readme, count=1)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root (tests use a temp tree)")
    args = parser.parse_args(argv)

    adr_dir = args.root / "docs" / "adr"
    readme_path = adr_dir / "README.md"
    adrs, problems = collect(adr_dir)
    current = readme_path.read_bytes().decode("utf-8")
    expected = render_readme(current, adrs)

    if args.write:
        if problems:
            print("\n".join(f"FAIL {p}" for p in problems), file=sys.stderr)
            return 1
        readme_path.write_bytes(expected.encode("utf-8"))
        print(f"wrote index of {len(adrs)} ADRs")
        return 0
    if current != expected:
        problems.append(
            "docs/adr/README.md index is out of date: run `python -m quality.tools.adr_index --write`"
        )
    for problem in problems:
        print(f"FAIL {problem}")
    if not problems:
        print(f"OK {len(adrs)} ADRs indexed")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
