"""Assemble the whole bundle in memory; ``sync`` writes it, ``check`` compares it with disk.

Pipeline: extract specs -> hash every source -> derive cross-reference blocks -> merge with existing
pages (preserving human prose) -> mark orphaned generated pages deprecated -> regenerate indexes.
The result is a ``{bundle-relative path: bytes}`` mapping and a list of human-readable notes.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import PurePosixPath
from typing import Any

from . import codelink as cl
from .extract import collect, describe_dir
from .pages import (
    GENERATOR,
    OKF_VERSION,
    PageSpec,
    Repo,
    dump_frontmatter,
    render_links,
    render_page,
    split_page,
)

LOG_SEED = """# Update log

## 2026-09-28
* **Creation**: Established the OKF v0.2 knowledge base for EIJA Studio, generated from code by `python -m quality.okf sync`. Pages are linked to code by `repo://` resources and content hashes; see [Knowledge base](/index.md).
"""

ROOT_INTRO = """This is the EIJA Studio knowledge base, a Google Cloud Open Knowledge Format (OKF) v0.2 bundle. Start retrieval here, then follow one section at a time.

Every concept page carries a `resource` (a `repo://` URI naming a file or symbol in this repository) and `sources` entries with the SHA-256 of the normalised code or document it describes. `nox -s okf` fails when a page's linked source changed since the page was baselined (STALE) and, after `python -m quality.okf sync` re-baselines the machine-owned parts, keeps failing (NOTES_STALE) while a page's hand-written `## Notes` have not been re-read against the new source: only `python -m quality.okf review` clears that. Hashing is per source: a page's hash covers its own symbol and the private helpers of the same module it reaches, not public callees, other modules or adapter bodies, so a passing gate never proves that every page is true. Machine-owned frontmatter and the blocks between `okf:generated` markers are regenerated by `python -m quality.okf sync`; prose under `## Notes` is human-owned and preserved.

A hash proves that the linked text changed, not that a page is right. Trust tiers come from the `verified` field, count only attestations bound to the page's current prose and source hashes, and `by: human:<id>` is a self-declared label the tool cannot authenticate. No current attestation means unverified."""


@dataclass
class Bundle:
    files: dict[str, str] = field(default_factory=dict)          # bundle-relative path -> text
    specs: list[PageSpec] = field(default_factory=list)
    digests: dict[str, dict[str, str]] = field(default_factory=dict)   # page path -> {resource: sha256}
    notes: list[str] = field(default_factory=list)
    deprecated: list[str] = field(default_factory=list)          # orphaned generated pages


def existing_pages(repo: Repo) -> dict[str, str]:
    found = {}
    if repo.bundle.is_dir():
        for path in sorted(repo.bundle.rglob("*.md")):
            found[path.relative_to(repo.bundle).as_posix()] = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    return found


def _inbound_links(specs: list[PageSpec], catalog: dict[str, PageSpec]) -> dict[str, set[str]]:
    """Page path -> the pages that link to it, checking that every generated link has a target."""
    inbound: dict[str, set[str]] = {}
    for spec in specs:
        targets = [(label, t) for label, paths in spec.out.items() for t in paths] + [("back", t) for t in spec.back]
        for label, target in targets:
            if target not in catalog:
                raise ValueError(f"{spec.path}: generated link to unknown page {target!r} ({label})")
            if target != spec.path:
                inbound.setdefault(target, set()).add(spec.path)
    return inbound


def _carry_over(bundle: Bundle, path: str, text: str) -> None:
    """A page on disk that no spec produces: deprecate an orphaned generated page, leave anything else alone."""
    try:
        meta, body = split_page(text)
    except ValueError:
        bundle.files[path] = text          # left untouched; the conformance gate reports it
        return
    if not (isinstance(meta.get("generated"), dict) and meta["generated"].get("by") == GENERATOR):
        bundle.files[path] = text                  # a hand-written concept page: left alone
        return
    if meta.get("status") != "deprecated":
        meta["status"] = "deprecated"
        bundle.notes.append(f"{path}: source no longer exists; marked deprecated (delete the page if the history is unwanted)")
    bundle.deprecated.append(path)
    bundle.files[path] = dump_frontmatter(reorder(meta)) + "\n" + body


def build(repo: Repo) -> Bundle:
    on_disk = existing_pages(repo)
    bundle = Bundle(specs=collect(repo))
    catalog = {s.path: s for s in bundle.specs}
    for spec in bundle.specs:
        bundle.digests[spec.path] = {src.resource: cl.digest(repo.root, cl.parse_uri(src.resource), src.method) for src in spec.sources}
    inbound = _inbound_links(bundle.specs, catalog)
    for spec in bundle.specs:
        blocks = {"facts": spec.facts, "links": render_links(spec, catalog, sorted(inbound.get(spec.path, ())))}
        bundle.files[spec.path] = render_page(spec, blocks, bundle.digests[spec.path], on_disk.get(spec.path))
    for path, text in on_disk.items():
        if path not in bundle.files and PurePosixPath(path).name not in ("index.md", "log.md"):
            _carry_over(bundle, path, text)
    bundle.files["log.md"] = on_disk.get("log.md", LOG_SEED)
    index_paths = _index_dirs(bundle.files)
    for directory in index_paths:
        bundle.files[(directory + "/" if directory else "") + "index.md"] = render_index(directory, bundle.files)
    return bundle


def reorder(meta: dict[str, Any]) -> dict[str, Any]:
    head = [k for k in ("type", "title", "description", "resource", "tags", "status", "generated", "sources") if k in meta]
    return {**{k: meta[k] for k in head}, **{k: v for k, v in meta.items() if k not in head}}


def _index_dirs(files: dict[str, str]) -> list[str]:
    dirs = {""}
    for path in files:
        parent = PurePosixPath(path).parent
        while str(parent) != ".":
            dirs.add(parent.as_posix())
            parent = parent.parent
    return sorted(dirs)


def render_index(directory: str, files: dict[str, str]) -> str:
    """Directory listing per OKF section 8: relative links with the concept's own description."""
    prefix = directory + "/" if directory else ""
    subdirs, concepts = _scan_directory(prefix, files)
    out: list[str] = []
    if directory == "":
        out.append(f'---\nokf_version: "{OKF_VERSION}"\n---\n')
        out.append("# Start here\n\n" + ROOT_INTRO + "\n")
    else:
        out.append(f"# {describe_dir(directory)}\n")
    if subdirs:
        rows = [f"* [{sub}]({sub}/) - {describe_dir(prefix + sub)}" for sub in sorted(subdirs)]
        out.append("# Sections\n\n" + "\n".join(rows) + "\n")
    if directory == "" and "log.md" in files:
        out.append("# History\n\n* [Update log](log.md) - dated changes to this bundle\n")
    out += _concept_sections(concepts)
    return "\n".join(out).rstrip("\n") + "\n"


def _scan_directory(prefix: str, files: dict[str, str]) -> tuple[set[str], list[tuple[str, str, str, str]]]:
    """(child directory names, (type, title, file name, description) of each concept page) directly under ``prefix``."""
    subdirs: set[str] = set()
    concepts: list[tuple[str, str, str, str]] = []
    for path, text in files.items():
        if not path.startswith(prefix):
            continue
        rest = path[len(prefix):]
        if "/" in rest:
            subdirs.add(rest.split("/", 1)[0])
        elif rest not in ("index.md", "log.md"):
            try:
                meta, _ = split_page(text)
            except ValueError:
                meta = {}
            concepts.append((str(meta.get("type", "Unknown")), str(meta.get("title", rest[:-3])), rest, str(meta.get("description", ""))))
    return subdirs, concepts


def _concept_sections(concepts: list[tuple[str, str, str, str]]) -> list[str]:
    """One '# Plural' list per concept type, entries sorted by file name."""
    groups: dict[str, list[tuple[str, str, str]]] = {}
    for kind, title, rest, description in concepts:
        groups.setdefault(kind, []).append((title, rest, description))
    out = []
    for kind in sorted(groups):
        entries = sorted(groups[kind], key=lambda e: (e[1]))
        out.append(f"# {_plural(kind)}\n\n" + "\n".join(f"* [{t}]({r}) - {d}" if d else f"* [{t}]({r})" for t, r, d in entries) + "\n")
    return out


_IRREGULAR_PLURALS = {"Acceptance Criterion": "Acceptance Criteria"}


def _plural(kind: str) -> str:
    if kind in _IRREGULAR_PLURALS:
        return _IRREGULAR_PLURALS[kind]
    return kind + "es" if kind.endswith(("s", "x")) else kind + "s"


def write(repo: Repo, bundle: Bundle) -> list[str]:
    """Write changed files (LF, UTF-8). Returns the bundle-relative paths that changed."""
    changed = []
    for path, text in sorted(bundle.files.items()):
        target = repo.bundle / path
        data = text.encode("utf-8")
        if target.exists() and target.read_bytes() == data:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        changed.append(path)
    return changed

