"""Generic policy: coherence with a domain pack's declared action catalog, the pack's laws, and declared effects.

Nothing here names a domain. Every state, role, action, effect and meaning comes from the pack (``domain.pack``);
without an explicit pack the configured default pack is used. Not generated by, or writable through, a provider.
"""
from __future__ import annotations
from collections.abc import Callable, Sequence
from typing import Any
from .models import Workflow, Transition, SemanticTransaction, DomainError
from .laws import Violation, evaluate_table
from .pack import Pack, default_pack
from .transactions import Transaction, apply_structural, refused


def _pack(pack: Pack | None) -> Pack:
    return pack if pack is not None else default_pack()


def __getattr__(name: str) -> Any:
    """``FORBIDDEN``: the default pack's forbidden effects. Kept only for verification/bend/bend_generate.py, whose bytes
    the committed Bend proof binds; WBS 1.4 regenerates that proof."""
    if name == "FORBIDDEN":
        return forbidden_effects()
    raise AttributeError(name)


def baseline(pack: Pack | None = None) -> Workflow:
    """The pack's baseline workflow."""
    return _pack(pack).model


def effects_table(pack: Pack | None = None) -> dict[str, tuple[str, ...]]:
    """Declared required effects per action."""
    return {a.id: a.required_effects for a in _pack(pack).actions}


def forbidden_effects(pack: Pack | None = None) -> tuple[str, ...]:
    return _pack(pack).effects.forbidden


def meaning_options(pack: Pack | None = None) -> dict[str, dict[str, Any]]:
    """The pack's meanings as the review surface shows them: label, whether supported, consequences."""
    return {m.id: {"label": m.label, "supported": m.supported, "consequences": list(m.consequences)} for m in _pack(pack).meanings}


def transition(action: str, source: str, target: str, role: str, pack: Pack | None = None, *,
               transition_id: str | None = None) -> Transition:
    """A transition for a declared action, with the action's declared guards and effects and the pack's forbidden effects."""
    p = _pack(pack)
    spec = p.action(action)
    if spec is None:
        raise DomainError("UNSUPPORTED_ACTION", "Action is not declared by the pack")
    return Transition(id=transition_id or "TR-" + action.upper(), action=action, from_state=source, to_state=target, role=role,
                      guards=spec.guards, required_effects=spec.required_effects, forbidden_effects=p.effects.forbidden)


def declared_codes(model: Workflow, pack: Pack) -> list[str]:
    """Every transition must perform a declared action, with exactly its declared guards and required effects,
    and must declare every pack-forbidden effect forbidden."""
    codes: list[str] = []
    for t in model.transitions:
        spec = pack.action(t.action)
        if spec is None:
            codes.append("UNSUPPORTED_ACTION")
            continue
        if set(t.guards) != set(spec.guards):
            codes.append("GUARD_POLICY:" + t.action)
        if set(t.required_effects) != set(spec.required_effects) or not set(pack.effects.forbidden) <= set(t.forbidden_effects):
            codes.append("EFFECT_POLICY:" + t.action)
    return codes


def law_violations(model: Workflow, pack: Pack | None = None) -> list[Violation]:
    return evaluate_table(_pack(pack).laws, model)


def check_policy(model: Workflow, pack: Pack | None = None) -> list[str]:
    """Sorted, de-duplicated policy codes of ``model`` under the pack (empty means the model conforms)."""
    p = _pack(pack)
    return sorted(set(declared_codes(model, p)) | {v.code for v in law_violations(model, p)})


def policy_refs(model: Workflow, pack: Pack | None = None) -> list[str]:
    """The laws and model elements a refusal points at (``law:<id>``, ``transition:<id>``, ``state:<id>``), sorted."""
    return sorted({ref for v in law_violations(model, pack) for ref in v.refs})


def ensure_policy(model: Workflow, pack: Pack | None = None) -> None:
    errors = check_policy(model, pack)
    if errors:
        raise DomainError("POLICY_BLOCKED", "; ".join(errors), details={"codes": errors, "refs": policy_refs(model, pack)})


def _declare(pack: Pack) -> Callable[[str, str, str, str, str], Transition]:
    """How an added transition gets its guards and effects: from the pack's declared action catalog."""
    def declare(transition_id: str, action: str, source: str, target: str, role: str) -> Transition:
        try:
            return transition(action, source, target, role, pack, transition_id=transition_id)
        except DomainError as error:
            raise refused(error.code, error.message, "transition:" + transition_id) from None
        except ValueError:
            raise refused("EDIT_INVALID", "The added transition is malformed", "transition:" + transition_id) from None
    return declare


def apply_structural_all(model: Workflow, transactions: Sequence[Transaction], pack: Pack | None = None) -> Workflow:
    """``model`` with every transaction applied in order; structure only, no policy (what-if and meaning previews)."""
    declare = _declare(_pack(pack))
    for tx in transactions:
        model = apply_structural(model, tx, declare)
    return model


def apply_transactions(model: Workflow, transactions: Sequence[Transaction], pack: Pack | None = None) -> Workflow:
    """Apply an edit sequence as one change: the start must conform, the result must conform (intermediate steps
    need only be coherent workflows). A refusal carries ``details`` {codes, refs} naming the laws it breaks."""
    p = _pack(pack)
    ensure_policy(model, p)
    candidate = apply_structural_all(model, transactions, p)
    ensure_policy(candidate, p)
    return candidate


def meaning_transactions(meaning_id: str, pack: Pack | None = None) -> tuple[Transaction, ...]:
    meaning = _pack(pack).meaning(meaning_id)
    if meaning is None:
        raise DomainError("MEANING_UNSUPPORTED", "This meaning is not modelled by the domain pack")
    return meaning.transactions


def apply_meaning(model: Workflow, meaning_id: str, pack: Pack | None = None) -> Workflow:
    """The candidate a supported pack meaning produces from ``model`` (policy-checked)."""
    meaning = _pack(pack).meaning(meaning_id)
    if meaning is None or not meaning.supported:
        raise DomainError("MEANING_UNSUPPORTED", "Only a supported meaning of the pack produces a candidate")
    return apply_transactions(model, meaning.transactions, pack)


def what_if(model: Workflow, meaning_id: str, pack: Pack | None = None) -> Workflow | None:
    """What an UNSUPPORTED meaning would do to ``model`` (structure only, never a candidate), or None when it
    declares no transactions or they do not even apply structurally."""
    meaning = _pack(pack).meaning(meaning_id)
    if meaning is None or meaning.supported or not meaning.transactions:
        return None
    try:
        return apply_structural_all(model, meaning.transactions, pack)
    except DomainError:
        return None


def apply_transaction(model: Workflow, tx: Transaction | SemanticTransaction, pack: Pack | None = None) -> Workflow:
    """Apply one transaction (policy-checked). The deprecated ``SemanticTransaction`` (only
    verification/bend/bend_generate.py still builds one; see models.py) means "the pack's first supported meaning"."""
    if isinstance(tx, SemanticTransaction):
        return apply_meaning(model, first_supported_meaning(pack), pack)
    return apply_transactions(model, (tx,), pack)


def first_supported_meaning(pack: Pack | None = None) -> str:
    """The id of the pack's first supported meaning (the demo candidate's meaning)."""
    first = next((m for m in _pack(pack).meanings if m.supported), None)
    if first is None:
        raise DomainError("MEANING_UNSUPPORTED", "The pack has no supported meaning")
    return first.id


def demo_candidate(pack: Pack | None = None) -> Workflow:
    """The pack's baseline with its first supported meaning applied."""
    return apply_meaning(baseline(pack), first_supported_meaning(pack), pack)


def projections(model: Workflow) -> dict[str, Any]:
    """Journey wording and rules derive from executable transitions, not AI copy."""
    return {
        "rules": [t.model_dump(mode="json") for t in model.transitions],
        "states": [{"id": state, "next_actions": [
            {"action": t.action, "role": t.role, "target": t.to_state}
            for t in model.transitions if t.from_state == state]} for state in model.states],
        "journeys": [f"{t.role}: {t.from_state} → {t.action} → {t.to_state}" for t in model.transitions],
    }


def _expected(question: Any, model: Workflow) -> str:
    if question.expected is not None:
        return str(question.expected)
    transition_id, field = question.expected_from
    found = next((t for t in model.transitions if t.id == transition_id), None)
    return "" if found is None else str(getattr(found, field))


def meaning_questions(model: Workflow, pack: Pack | None = None) -> list[dict[str, Any]]:
    """The pack's meaning-check questions, with expected answers read from the model where the pack says so."""
    return [{"id": q.id, "question": q.question, "expected": _expected(q, model)} for q in _pack(pack).journey.questions]
