"""Generic policy: coherence with a domain pack's declared action catalog, the pack's laws, and declared effects.

Nothing here names a domain. Every state, role, action, effect and meaning comes from the pack (``domain.pack``);
without an explicit pack the configured default pack is used. Not generated by, or writable through, a provider.
"""
from __future__ import annotations
from typing import Any
from .models import Workflow, Transition, SemanticTransaction, DomainError
from .laws import Violation, evaluate_table
from .pack import Pack, default_pack


def _pack(pack: Pack | None) -> Pack:
    return pack if pack is not None else default_pack()


def __getattr__(name: str) -> Any:
    """``FORBIDDEN``: the default pack's forbidden effects. Kept only for verification/bend/bend_generate.py, whose bytes
    the committed Bend proof binds; WBS 1.4 regenerates that proof."""
    if name == "FORBIDDEN":
        return forbidden_effects()
    raise AttributeError(name)


def baseline(pack: Pack | None = None) -> Workflow:
    """The pack's baseline workflow."""
    return _pack(pack).model


def effects_table(pack: Pack | None = None) -> dict[str, tuple[str, ...]]:
    """Declared required effects per action."""
    return {a.id: a.required_effects for a in _pack(pack).actions}


def forbidden_effects(pack: Pack | None = None) -> tuple[str, ...]:
    return _pack(pack).effects.forbidden


def meaning_options(pack: Pack | None = None) -> dict[str, dict[str, Any]]:
    """The pack's meanings as the review surface shows them: label, whether supported, consequences."""
    return {m.id: {"label": m.label, "supported": m.supported, "consequences": list(m.consequences)} for m in _pack(pack).meanings}


def transition(action: str, source: str, target: str, role: str, pack: Pack | None = None) -> Transition:
    """A transition for a declared action, with the action's declared guards and effects and the pack's forbidden effects."""
    p = _pack(pack)
    spec = p.action(action)
    if spec is None:
        raise DomainError("UNSUPPORTED_ACTION", "Action is not declared by the pack")
    return Transition(id="TR-" + action.upper(), action=action, from_state=source, to_state=target, role=role,
                      guards=spec.guards, required_effects=spec.required_effects, forbidden_effects=p.effects.forbidden)


def declared_codes(model: Workflow, pack: Pack) -> list[str]:
    """Every transition must perform a declared action, with exactly its declared guards and required effects,
    and must declare every pack-forbidden effect forbidden."""
    codes: list[str] = []
    for t in model.transitions:
        spec = pack.action(t.action)
        if spec is None:
            codes.append("UNSUPPORTED_ACTION")
            continue
        if set(t.guards) != set(spec.guards):
            codes.append("GUARD_POLICY:" + t.action)
        if set(t.required_effects) != set(spec.required_effects) or not set(pack.effects.forbidden) <= set(t.forbidden_effects):
            codes.append("EFFECT_POLICY:" + t.action)
    return codes


def law_violations(model: Workflow, pack: Pack | None = None) -> list[Violation]:
    return evaluate_table(_pack(pack).laws, model)


def check_policy(model: Workflow, pack: Pack | None = None) -> list[str]:
    """Sorted, de-duplicated policy codes of ``model`` under the pack (empty means the model conforms)."""
    p = _pack(pack)
    return sorted(set(declared_codes(model, p)) | {v.code for v in law_violations(model, p)})


def policy_refs(model: Workflow, pack: Pack | None = None) -> list[str]:
    """The laws and model elements a refusal points at (``law:<id>``, ``transition:<id>``, ``state:<id>``), sorted."""
    return sorted({ref for v in law_violations(model, pack) for ref in v.refs})


def ensure_policy(model: Workflow, pack: Pack | None = None) -> None:
    errors = check_policy(model, pack)
    if errors:
        raise DomainError("POLICY_BLOCKED", "; ".join(errors), details={"codes": errors, "refs": policy_refs(model, pack)})


def apply_transaction(model: Workflow, tx: SemanticTransaction, pack: Pack | None = None) -> Workflow:
    """Legacy closed vocabulary (two kinds), kept until the open vocabulary of WBS 1.3 replaces it: the recommendation
    meaning of the default pack and a rejection-source edit."""
    p = _pack(pack)
    ensure_policy(model, p)
    by = {t.action: t for t in model.transitions}
    if tx.kind == "enable_recommendation":
        by["Recommend"] = transition("Recommend", "Submitted", "Recommended", "Teacher", p)
        by["Approve"] = transition("Approve", "Recommended", "Approved", "Registrar", p)
    elif "Recommend" not in by:
        raise DomainError("MEANING_REQUIRED", "Enable the recommendation meaning first")
    by["Reject"] = transition("Reject", tx.rejection_source, "Rejected", "Registrar", p)
    candidate = Workflow(id=model.id, initial_state=model.initial_state,
                         states=("Draft", "Submitted", "Recommended", "Approved", "Rejected"), transitions=tuple(by.values()))
    ensure_policy(candidate, p)
    return candidate


def projections(model: Workflow) -> dict[str, Any]:
    """Journey wording and rules derive from executable transitions, not AI copy."""
    return {
        "rules": [t.model_dump(mode="json") for t in model.transitions],
        "states": [{"id": state, "next_actions": [
            {"action": t.action, "role": t.role, "target": t.to_state}
            for t in model.transitions if t.from_state == state]} for state in model.states],
        "journeys": [f"{t.role}: {t.from_state} → {t.action} → {t.to_state}" for t in model.transitions],
    }


def _expected(question: Any, model: Workflow) -> str:
    if question.expected is not None:
        return str(question.expected)
    transition_id, field = question.expected_from
    found = next((t for t in model.transitions if t.id == transition_id), None)
    return "" if found is None else str(getattr(found, field))


def meaning_questions(model: Workflow, pack: Pack | None = None) -> list[dict[str, Any]]:
    """The pack's meaning-check questions, with expected answers read from the model where the pack says so."""
    return [{"id": q.id, "question": q.question, "expected": _expected(q, model)} for q in _pack(pack).journey.questions]
