"""Protected excursion policy. Not generated by, or writable through, a provider."""
from __future__ import annotations
from typing import Any
from .models import Workflow, Transition, BASE_GUARDS, SemanticTransaction, DomainError
from .laws import Violation, evaluate_table
from .pack import Pack

FORBIDDEN = ("PaymentCaptured", "ParentDataExported")
EFFECTS = {
    "Submit": ("Audit:ExcursionSubmitted",),
    "Recommend": ("Audit:ExcursionRecommended", "Notification:RegistrarQueued"),
    "Approve": ("Audit:ExcursionApproved",),
    "Reject": ("Audit:ExcursionRejected",),
    "Revise": ("Audit:ExcursionReopened",),
}
CANONICAL_OPTIONS: dict[str, dict[str, Any]] = {
    "recommend_only": {"label": "Teacher recommends; registrar decides", "supported": True,
        "consequences": ["Only active, assigned teachers recommend.", "Registrar approval AND rejection initially require Recommended.", "Teachers do not receive final approval authority."]},
    "final_approval": {"label": "Teacher grants final approval", "supported": False,
        "consequences": ["Expands protected authority; blocked by this POC's policy."]},
    "confirm_only": {"label": "Teacher confirms a completed section", "supported": False,
        "consequences": ["A different domain operation; not implemented by this bounded POC."]},
    "unsupported": {"label": "Outside the modelled scope", "supported": False,
        "consequences": ["Requires domain and source-level engineering; no automatic application."]},
}


def transition(action: str, source: str, target: str, role: str) -> Transition:
    return Transition(id="TR-" + action.upper(), action=action, from_state=source, to_state=target,
                      role=role, guards=BASE_GUARDS + (("actor_assigned",) if action == "Recommend" else ()),
                      required_effects=EFFECTS[action], forbidden_effects=FORBIDDEN)


def baseline() -> Workflow:
    return Workflow(states=("Draft", "Submitted", "Approved", "Rejected"), transitions=(
        transition("Submit", "Draft", "Submitted", "Teacher"),
        transition("Approve", "Submitted", "Approved", "Registrar"),
        transition("Reject", "Submitted", "Rejected", "Registrar"),
        transition("Revise", "Rejected", "Draft", "Teacher"),
    ))


def check_policy(model: Workflow) -> list[str]:
    errors: list[str] = []
    by = {t.action: t for t in model.transitions}
    candidate = "Recommend" in by
    expected_actions = {"Submit", "Approve", "Reject", "Revise"} | ({"Recommend"} if candidate else set())
    expected_states = {"Draft", "Submitted", "Approved", "Rejected"} | ({"Recommended"} if candidate else set())
    if set(by) != expected_actions or set(model.states) != expected_states or model.initial_state != "Draft":
        errors.append("UNSUPPORTED_WORKFLOW_SHAPE")
    expected = {
        "Submit": ("Teacher", "Draft", "Submitted"),
        "Revise": ("Teacher", "Rejected", "Draft"),
        "Approve": ("Registrar", "Recommended" if candidate else "Submitted", "Approved"),
        "Reject": ("Registrar", None if candidate else "Submitted", "Rejected"),
        "Recommend": ("Teacher", "Submitted", "Recommended"),
    }
    for action, t in by.items():
        if action not in expected:
            errors.append("UNSUPPORTED_ACTION"); continue
        role, source, target = expected[action]
        if t.role != role:
            errors.append("PROTECTED_AUTHORITY:" + action)
        if t.to_state != target or (source is not None and t.from_state != source):
            errors.append("PROTECTED_STATE:" + action)
        if action == "Reject" and t.from_state not in {"Recommended", "Submitted"}:
            errors.append("UNSUPPORTED_REJECTION_SOURCE")
        expected_guards = set(BASE_GUARDS) | ({"actor_assigned"} if action == "Recommend" else set())
        if set(t.guards) != expected_guards:
            errors.append("GUARD_POLICY:" + action)
        if set(t.required_effects) != set(EFFECTS[action]) or not set(FORBIDDEN).issubset(t.forbidden_effects):
            errors.append("EFFECT_POLICY:" + action)
    return sorted(set(errors))


def ensure_policy(model: Workflow) -> None:
    errors = check_policy(model)
    if errors:
        raise DomainError("POLICY_BLOCKED", "; ".join(errors))


def apply_transaction(model: Workflow, tx: SemanticTransaction) -> Workflow:
    ensure_policy(model)
    by = {t.action: t for t in model.transitions}
    if tx.kind == "enable_recommendation":
        by["Recommend"] = transition("Recommend", "Submitted", "Recommended", "Teacher")
        by["Approve"] = transition("Approve", "Recommended", "Approved", "Registrar")
    elif "Recommend" not in by:
        raise DomainError("MEANING_REQUIRED", "Enable the recommendation meaning first")
    by["Reject"] = transition("Reject", tx.rejection_source, "Rejected", "Registrar")
    candidate = Workflow(states=("Draft", "Submitted", "Recommended", "Approved", "Rejected"), transitions=tuple(by.values()))
    ensure_policy(candidate)
    return candidate


def projections(model: Workflow) -> dict[str, Any]:
    """Journey wording and rules derive from executable transitions, not AI copy."""
    return {
        "rules": [t.model_dump(mode="json") for t in model.transitions],
        "states": [{"id": state, "next_actions": [
            {"action": t.action, "role": t.role, "target": t.to_state}
            for t in model.transitions if t.from_state == state]} for state in model.states],
        "journeys": [f"{t.role}: {t.from_state} → {t.action} → {t.to_state}" for t in model.transitions],
    }


def meaning_questions(model: Workflow) -> list[dict[str, Any]]:
    by = {t.action: t for t in model.transitions}
    return [
        {"id": "authority", "question": "Who retains final approval authority?", "expected": "Registrar"},
        {"id": "assignment", "question": "Can an unassigned teacher recommend?", "expected": "No"},
        {"id": "reject_entry", "question": "Which state must precede registrar rejection?", "expected": by["Reject"].from_state},
    ]


# ---- pack-driven policy (WBS 1.1): coherence with the declared catalog + the pack's laws ----------------------

def declared_codes(model: Workflow, pack: Pack) -> list[str]:
    """Every transition must perform a declared action, with exactly its declared guards and required effects,
    and must declare every pack-forbidden effect forbidden."""
    codes: list[str] = []
    for t in model.transitions:
        spec = pack.action(t.action)
        if spec is None:
            codes.append("UNSUPPORTED_ACTION")
            continue
        if set(t.guards) != set(spec.guards):
            codes.append("GUARD_POLICY:" + t.action)
        if set(t.required_effects) != set(spec.required_effects) or not set(pack.effects.forbidden) <= set(t.forbidden_effects):
            codes.append("EFFECT_POLICY:" + t.action)
    return codes


def law_violations(model: Workflow, pack: Pack) -> list[Violation]:
    return evaluate_table(pack.laws, model)


def pack_policy(model: Workflow, pack: Pack) -> list[str]:
    """Sorted, de-duplicated policy codes of ``model`` under ``pack``."""
    return sorted(set(declared_codes(model, pack)) | {v.code for v in law_violations(model, pack)})
