"""Mermaid: the pack as a Markdown page of `stateDiagram-v2` and `classDiagram` blocks, and back (ADR-0190).

Mermaid renders in GitHub, GitLab and most wikis, so a model exported this way can live in a README or design doc and
be read by anyone. It is checked against Mermaid's own parser (`verification/interop/mermaid_oracle.py`): what
Mermaid reads from the export must be what PlayIDE reads.

Mermaid has no use case diagram and no notes on attributes, so those are listed in the export's report as not
carried. Everything else in the PlantUML export is here too.
"""
from __future__ import annotations

import html
import re
from dataclasses import replace
from typing import Any

from eija_studio.domain.data import DataModel, Entity
from eija_studio.domain.models import Workflow
from eija_studio.domain.pack import Pack

from .model import (GENERATOR, Klass, Parsed, attribute_type, enumerations, export_report, multiplicity, terminals,
                    transition_label)
from .textual import read_body, read_relation, read_transition

_PLAIN = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
_ESCAPE = {"#": "#35;", ";": "#59;", '"': "#quot;", "<": "#lt;", ">": "#gt;", "{": "#123;", "}": "#125;", "`": "#96;"}
_RESERVED = {"end", "state", "class", "note", "direction", "classdef", "style", "default"}
_FENCE = re.compile(r"^```\s*mermaid\s*$(?P<body>.*?)^```\s*$", re.MULTILINE | re.DOTALL)


def _text(text: str) -> str:
    return re.sub(r'[#;"<>{}`]', lambda m: _ESCAPE[m.group()], " ".join(text.split()))


def unescape(text: str) -> str:
    text = re.sub(r"#(\d+);", lambda m: chr(int(m.group(1))), text)
    return re.sub(r"#(\w+);", lambda m: html.unescape(f"&{m.group(1)};"), text)


def _alias(name: str) -> str:
    return name if _PLAIN.match(name) and name.lower() not in _RESERVED else "s_" + name.encode("utf-8").hex()


def _states(model: Workflow) -> list[str]:
    out = ["stateDiagram-v2"]
    out += [f'    state "{_text(s)}" as {_alias(s)}' for s in model.states if _alias(s) != s]
    out += [f"    {s}" for s in model.states if _alias(s) == s]
    out.append(f"    [*] --> {_alias(model.initial_state)}")
    for t in sorted(model.transitions, key=lambda t: t.id):
        out.append(f"    {_alias(t.from_state)} --> {_alias(t.to_state)} : {_text(transition_label(t))}")
    return out + [f"    {_alias(s)} --> [*]" for s in terminals(model)]


def _class(entity: Entity, record: bool, enums: dict[tuple[str, str], str]) -> list[str]:
    out = [f"    class {entity.name} {{"] + (["        <<record>>"] if record else [])
    for a in entity.attributes:
        bound = f" maxLength={a.max_length}" if a.type == "text" else ""
        out.append(f"        +{a.name} : {attribute_type(entity.name, a, enums)} [{multiplicity(a)}]{bound}")
    return [*out, "    }"]


def _classes(data: DataModel) -> list[str]:
    enums = enumerations(data)
    out = ["classDiagram"]
    for entity in data.entities:
        out += _class(entity, entity.name == data.record, enums)
    for (entity_name, attribute), name in sorted(enums.items(), key=lambda kv: kv[1]):
        choices = next(a.choices for a in data.entity(entity_name).attributes if a.name == attribute)
        out += [f"    class {name} {{", "        <<enumeration>>", *(f"        {_text(c)}" for c in choices), "    }"]
    arrows = {"composition": "*--", "aggregation": "o--", "association": "-->"}
    for link in data.associations:
        role = f" : {_text(link.role)}" if link.role else ""
        out.append(f'    {link.source} "{link.source_multiplicity}" {arrows[link.kind]} "{link.target_multiplicity}" {link.target}{role}')
    return out + [f'    note for {e.name} "{_text(e.description)}"' for e in data.entities if e.description]


def export(pack: Pack, model: Workflow, data: DataModel | None) -> tuple[str, dict[str, Any]]:
    parts = [f"<!-- GENERATED by {GENERATOR} from pack {pack.id} {pack.pack.version}, model {model.semantic_hash}. -->",
             f"# {pack.pack.name}", "", "## State machine", "", "```mermaid", *_states(model), "```"]
    if data is not None:
        parts += ["", "## Class model", "", "```mermaid", *_classes(data), "```"]
    extra = ["the use case diagram (Mermaid has none; export PlantUML, XMI or draw.io for it)"]
    others = [f"{r.id} «{r.kind}»" for r in pack.roles if r.kind != "human"]
    if others:  # ADR-0210: the kinds live on the use case diagram's actors
        extra.append("the kinds of actor that are not people, " + ", ".join(others) + " (they are on the use case diagram)")
    if data is not None and any(a.description for e in data.entities for a in e.attributes):
        extra.append("attribute descriptions (Mermaid has no notes on attributes)")
    return "\n".join(parts) + "\n", export_report("mermaid", pack, model, data, *extra)


# ---- reading ------------------------------------------------------------------------------------------------

def _blocks(text: str) -> list[list[tuple[str, str]]]:
    fenced = list(_FENCE.finditer(text))
    spans = [(m.start("body"), m.group("body")) for m in fenced] or [(0, text)]
    blocks = []
    for start, body in spans:
        first = text.count("\n", 0, start) + 1
        lines = [(raw.strip(), f"line {first + n}") for n, raw in enumerate(body.splitlines())]
        blocks.append([(line, where) for line, where in lines if line and not line.startswith("%%")])
    return blocks


_STATE_DECL = re.compile(r'^state\s+(?:"(?P<label>[^"]+)"\s+as\s+(?P<alias>\S+)|(?P<name>[^\s{:<"]+))\s*(?P<rest>.*)$')
_PRESENTATION = re.compile(r"^(direction|classDef|class\s+\S+\s+\w+$|style|linkStyle|title|accTitle|accDescr|---)\b")


def _state_decl(line: str, where: str, parsed: Parsed, aliases: dict[str, str], depth: list[int]) -> bool:
    found = _STATE_DECL.match(line)
    if found is None:
        return False
    name = unescape(found.group("label")) if found.group("label") else found.group("name")
    if found.group("alias"):
        aliases[found.group("alias")] = name
    rest = found.group("rest")
    if "<<" in rest:
        parsed.skip(where, line, "pseudostates (choice, fork, join) are not in PlayIDE's state vocabulary")
    elif rest.startswith("{"):
        depth[0] += 1
        parsed.skip(where, f"composite state {name}", "composite states are planned (issue #93); its contents are not imported")
    else:
        parsed.state(name)
    return True


def _state_line(line: str, where: str, parsed: Parsed, aliases: dict[str, str], depth: list[int]) -> None:
    line = re.sub(r":::\w+", "", line)
    if _state_decl(line, where, parsed, aliases, depth) or read_transition(line, where, parsed, aliases, unescape):
        return
    if line.startswith("note") or line == "end note":
        parsed.skip(where, line, "notes on a state machine are not carried")
    elif re.match(r"^[^\s:]+\s*:\s*\S", line):
        parsed.skip(where, line, "state descriptions are not carried")
    elif re.fullmatch(r"[A-Za-z_]\w*", line):
        parsed.state(aliases.get(line, line))
    elif not _PRESENTATION.match(line) and line not in ("--",):
        parsed.skip(where, line, "not a PlayIDE state machine element")


def _read_states(block: list[tuple[str, str]], parsed: Parsed) -> None:
    aliases: dict[str, str] = {}
    depth = [0]
    if parsed.states is None:
        parsed.states = []
    for line, where in block[1:]:
        if depth[0]:
            depth[0] += line.count("{") - line.count("}")
            continue
        _state_line(line, where, parsed, aliases, depth)


_CLASS = re.compile(r"^class\s+(?P<name>\w+)(?:~[^~]*~)?(?:\[\"[^\"]*\"\])?\s*(?P<open>\{)?\s*$")
_MEMBER = re.compile(r"^(?P<name>\w+)\s*:\s*(?P<member>.+)$")
_NOTE = re.compile(r'^note\s+for\s+(?P<target>\w+)\s+"(?P<text>[^"]*)"\s*$')
_ANNOTATION = re.compile(r"^<<\s*(?P<what>[\w ]+?)\s*>>\s*(?P<name>\w+)\s*$")


class _ClassBlock:
    def __init__(self) -> None:
        self.bodies: dict[str, list[tuple[str, str]]] = {}
        self.order: list[str] = []
        self.notes: dict[str, str] = {}

    def body(self, name: str, where: str) -> list[tuple[str, str]]:
        if name not in self.bodies:
            self.bodies[name] = []
            self.order.append(name)
        return self.bodies[name]


def _class_body(lines: list[tuple[str, str]], i: int, found: re.Match[str], block: _ClassBlock) -> int:
    """`class X {` and its member lines up to `}`; the index of the line after it."""
    body = block.body(found.group("name"), lines[i][1])
    if not found.group("open"):
        return i + 1
    end = next((j for j in range(i + 1, len(lines)) if lines[j][0] == "}"), len(lines))
    body += [(unescape(line), where) for line, where in lines[i + 1:end]]
    return end + 1


def _class_line(lines: list[tuple[str, str]], i: int, block: _ClassBlock, parsed: Parsed) -> int:
    line, where = lines[i]
    if (found := _CLASS.match(line)) is not None:
        return _class_body(lines, i, found, block)
    if (note := _NOTE.match(line)) is not None:
        block.notes[note.group("target")] = unescape(note.group("text"))
    elif (annotation := _ANNOTATION.match(line)) is not None:
        block.body(annotation.group("name"), where).insert(0, (f"<<{annotation.group('what')}>>", where))
    elif read_relation(line, where, parsed):
        pass
    elif (member := _MEMBER.match(line)) is not None:
        block.body(member.group("name"), where).append((unescape(member.group("member")), where))
    elif line.startswith("note"):
        parsed.skip(where, line, "a note on no class is not carried")
    elif not _PRESENTATION.match(line):
        parsed.skip(where, line, "not a PlayIDE class model element")
    return i + 1


def _read_classes(block: list[tuple[str, str]], parsed: Parsed) -> None:
    found = _ClassBlock()
    i = 1
    while i < len(block):
        i = _class_line(block, i, found, parsed)
    if parsed.classes is None:
        parsed.classes = []
    for name in found.order:
        lines = found.bodies[name]
        if any(re.match(r"^<<\s*(interface|abstract)\s*>>$", line.lower()) for line, _ in lines):
            parsed.skip(lines[0][1], f"interface {name}", "interfaces and abstract classes are not in PlayIDE's data vocabulary")
        else:
            read_body(name, lines or [("", "")], parsed, record=False, enum=False)
    _apply_notes(found.notes, parsed.classes, parsed)


def _apply_notes(notes: dict[str, str], classes: list[Klass], parsed: Parsed) -> None:
    for target, text in notes.items():
        index = next((i for i, k in enumerate(classes) if k.name == target), None)
        if index is None:
            parsed.skip("class model", f"note for {target}", "it is not attached to an imported class")
        else:
            classes[index] = replace(classes[index], description=text)


def parse(text: str) -> Parsed:
    parsed = Parsed()
    for block in _blocks(text):
        if not block:
            continue
        head, where = block[0][0].split()[0], block[0][1]
        if head in ("stateDiagram", "stateDiagram-v2"):
            _read_states(block, parsed)
        elif head == "classDiagram":
            _read_classes(block, parsed)
        else:
            parsed.skip(where, head, "only Mermaid state and class diagrams are UML that PlayIDE reads")
    return parsed
