"""Canonical JSON report, deterministic Markdown rendering, snapshot publishing and the drift check.

`build_report` is pure over a `journey.collect()` result. `render_markdown` is pure over the report
JSON, so the committed docs/hci/REPORT.md can be re-rendered from the committed snapshot and compared
byte for byte (`python -m quality.hci check`), without a browser.
"""
from __future__ import annotations

import json
from pathlib import Path

from . import analysis, budgets, recommend

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs" / "hci"
SNAPSHOT = DOCS / "report.snapshot.json"
REPORT_MD = DOCS / "REPORT.md"
SCHEMA = "eija.hci.report.v1"

LIMITATIONS = [
    "Every law is a population-average model from laboratory studies. Predicted times rank alternatives; they are not measurements of any user.",
    "This is NOT a human usability study. No participant, persona or task-success rate is represented (human study: NOT_RUN).",
    "The journey answers the three review questions with scripted fixture text; it exercises the UI and says nothing about comprehension.",
    "Approval and apply run under the kernel-test harness identity (source differs from the owner-stamped fixture); they are UI evidence, not a release approval.",
    "Doherty timings are wall-clock on one shared Windows PC, headless Chrome, loopback server; they exclude OS/input latency and are sensitive to load.",
    "axe-core detects only a subset of WCAG failures; a clean axe run is not conformance. Exceptions to 2.5.8 other than spacing are not evaluated.",
    "The working-memory number is a visibility-based heuristic proxy for Miller/Cowan chunk limits, not a measure of anyone's memory.",
]
NOT_RUN = [
    "Human usability study / think-aloud / task-success rate: NOT_RUN (needs participants; see docs/hci/README.md protocol notes)",
    "Screen-reader testing (NVDA, JAWS, VoiceOver, TalkBack): NOT_RUN",
    "Browsers other than Google Chrome (Firefox, Safari/WebKit): NOT_RUN",
    "Real touch devices and 400% browser zoom (only 390x844 and 320x568 viewport emulation ran): NOT_RUN",
    "Forced-colors / high-contrast and prefers-reduced-motion audits: NOT_RUN",
    "Live model provider round-trips (offline synthetic provider only): NOT_RUN",
    "Release-stamped identity (real `eija serve` approval): NOT_RUN on unstamped source; use --identity release on a stamped build",
]


def build_report(raw: dict, date: str | None = None, budget_defs: list[dict] | None = None) -> dict:
    metrics = analysis.analyse(raw)
    report = {"schema": SCHEMA, "date": date, **metrics}
    report["recommendations"] = recommend.recommend(metrics)
    report["budgets"] = budgets.evaluate(report, budget_defs)
    report["limitations"] = LIMITATIONS
    report["not_run"] = NOT_RUN
    return report


def dumps(obj: dict) -> str:
    """Canonical JSON: sorted keys, 2-space indent, LF, trailing newline."""
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))  # bytes: never CRLF on Windows


# --- Markdown -----------------------------------------------------------------------------------
def _table(headers: list[str], rows: list[list]) -> str:
    def cell(x) -> str:
        return ("-" if x is None else str(x)).replace("|", "\\|").replace("\n", " ")
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def _fmt(x, unit="") -> str:
    return "-" if x is None else f"{x}{unit}"


def render_markdown(rep: dict) -> str:
    rep = json.loads(dumps(rep))  # render only what the canonical JSON holds (sorted keys), so in-memory and snapshot agree
    env = rep["environment"]
    fit, hk, kl, wc, kb, wm, dh = (rep["fitts"], rep["hick_hyman"], rep["klm"], rep["wcag"], rep["keyboard"],
                                   rep["working_memory"], rep["measured"]["doherty"])
    out: list[str] = []
    add = out.append
    add("# HCI report: Studio UI journey")
    add("")
    add("> Generated by `python -m quality.hci run --publish-docs` from `docs/hci/report.snapshot.json`; "
        "re-rendered and drift-checked by `python -m quality.hci check`. Do not edit by hand.")
    add("")
    add(f"Evidence kind: **model-based prediction plus instrumented measurement on synthetic data**. Not a human study. "
        f"Identity under test: `{env['identity_source']}`. Snapshot date: {rep['date'] or 'not stamped'}.")
    add("")
    add("## Environment")
    add("")
    add(_table(["Item", "Value"], [
        ["Platform", env["platform"]], ["Browser", f"Google Chrome {env['chrome']} (headless={env['headless']})"],
        ["Playwright / axe", f"{env['playwright']} / axe-core {env['axe_core']} via axe-playwright-python {env['axe_playwright_python']}"],
        ["Viewport", f"{env['viewport']['width']}x{env['viewport']['height']} @ {env['device_scale_factor']}x"],
        ["Provider", env["provider"]], ["Pointer repeats (timing)", env["repeats"]],
        ["UI bytes (sha256, first 12)", ", ".join(f"{k} {v[:12]}" for k, v in sorted(env["ui_sha256"].items()))]]))
    add("")
    add("## Headline")
    add("")
    add(_table(["Law / standard", "Metric", "Value", "Threshold", "Flag"], [
        ["Fitts (Shannon)", "pointer moves with ID > 4 bits", fit["summary"]["moves_id_over_4"], "0", "FLAG" if fit["summary"]["moves_id_over_4"] else "ok"],
        ["Fitts / WCAG 2.5.8", "pointer targets with W < 24 px", fit["summary"]["targets_w_under_24"], "0", "FLAG" if fit["summary"]["targets_w_under_24"] else "ok"],
        ["Hick-Hyman", "choice groups with n > 7", hk["summary"]["choice_points_over_7"], "0", "FLAG" if hk["summary"]["choice_points_over_7"] else "ok"],
        ["KLM-GOMS", "predicted expert time, pointer journey (s)", kl["expert_time_pointer_s"], "-", "info"],
        ["KLM-GOMS", "predicted expert time, keyboard-only (s)", kl["expert_time_keyboard_only_s"], "-", "info"],
        ["Doherty", "click -> settled DOM p95 (ms)", dh["settled_p95_ms"], "400", "FLAG" if (dh["settled_p95_ms"] or 0) > 400 else "ok"],
        ["Doherty", "click -> first feedback p95 (ms)", dh["first_feedback_p95_ms"], "400", "FLAG" if (dh["first_feedback_p95_ms"] or 0) > 400 else "ok"],
        ["WCAG 2.2 AA (axe)", "violating rules (critical/serious/moderate/minor)",
         f"{wc['summary']['rules']} ({wc['summary']['critical']}/{wc['summary']['serious']}/{wc['summary']['moderate']}/{wc['summary']['minor']})", "0",
         "FLAG" if wc["summary"]["rules"] else "ok"],
        ["WCAG 2.5.8", "targets failing minimum size", wc["summary"]["target_size_failures"], "0", "FLAG" if wc["summary"]["target_size_failures"] else "ok"],
        ["Keyboard", "activations that dropped focus", f"{kb['focus_lost_count']}/{kb['activations']}", "0", "FLAG" if kb["focus_lost_count"] else "ok"],
        ["Working memory (proxy)", "max chunks visible at once", wm["summary"]["max_chunks_viewport"], "9", "FLAG" if wm["summary"]["views_over_miller_9"] else "ok"],
    ]))
    add("")
    add("## Ranked recommendations")
    add("")
    add("Severity 5 critical WCAG, 4 serious WCAG / focus loss / wait over 1 s, 3 moderate WCAG / 2.5.8 / wait over 400 ms, 2 law flag, 1 informational. "
        "Ties broken by predicted saving (a model output), then id. Applying these belongs to the visual lane's next wave.")
    add("")
    add(_table(["#", "Sev", "Recommendation", "Category", "Predicted effect"],
               [[x["rank"], x["severity"], x["title"], x["category"], x["predicted_effect"] or (f"{x['predicted_saving_s']} s" if x["predicted_saving_s"] else "-")]
                for x in rep["recommendations"]]))
    add("")
    for x in rep["recommendations"]:
        add(f"### {x['rank']}. {x['title']}")
        add("")
        add(f"- Change: {x['change']}")
        add(f"- Evidence: `{json.dumps(x['evidence'], sort_keys=True, ensure_ascii=False)}`")
        if x["targets"]:
            add(f"- Targets: {', '.join(f'`{t}`' for t in x['targets'][:12])}")
        add(f"- Laws: {', '.join(x['laws']) or '-'}; predicted saving (model): {x['predicted_saving_s']} s")
        add("")
    add("## Budgets")
    add("")
    add("`target` is the law's threshold; `limit` is the current ratchet (`quality/hci/budgets.json`). GAP = known shortfall within the ratchet; FAIL = regression.")
    add("")
    add(_table(["Budget", "Law", "Value", "Target", "Limit", "Status"],
               [[b["id"], b["law"], f"{_fmt(b['value'])} {b['unit']}", b["target"], b["limit"], b["status"]] for b in rep["budgets"]]))
    add("")
    add("## Fitts's law")
    add("")
    m = fit["model"]
    add(f"`{m['form']}`, a = {m['a_s']} s, b = {m['b_s_per_bit']} s/bit ({m['citation']}). D = distance between consecutive pointer landing points "
        f"(centre of the clickable box); W = smaller side of the target's effective box (a checkbox and its label are one target).")
    add("")
    add(_table(["Step", "Target", "D px", "W px", "ID bits", "MT s", "2.5.8", "Flags"],
               [[t["step"], t["target"][:38], t["distance_px"], t["w_px"], t["id_bits"], t["predicted_mt_s"], t["wcag_2_5_8"], ", ".join(t["flags"]) or "-"] for t in fit["targets"]]))
    add("")
    s = fit["summary"]
    add(f"Mean ID {s['mean_id_bits']} bits, hardest move `{s['max_id_step']}` ({s['max_id_bits']} bits), predicted pointing time {s['predicted_pointing_time_s']} s over "
        f"{s['total_distance_px']} px, {s['scrolls_needed']} scroll(s) needed (not modelled).")
    add("")
    add("## Hick-Hyman law")
    add("")
    add(f"`{hk['model']['form']}`, b = {hk['model']['b_s_per_bit']} s/bit ({hk['model']['citation']}). {hk['model']['note']}.")
    add("")
    add(_table(["Step", "Decision", "n", "bits", "T s", "n > 7", "Screen controls", "Screen T s"],
               [[d["step"], d["decision"], d["choices"], d["bits"], d["predicted_s"], "FLAG" if d["over_7"] else "ok", d["screen_controls"], d["screen_predicted_s"]] for d in hk["decisions"]]))
    add("")
    add(f"Predicted total choice time {hk['summary']['predicted_choice_time_s']} s; largest choice group {hk['summary']['max_choices']}.")
    add("")
    add("## KLM-GOMS")
    add("")
    t = kl["times_s"]
    add(f"Operator times (s): K {t['K']}, P {t['P']}, B {t['B']}, H {t['H']}, M {t['M']} ({kl['citation']}). {kl['placement_rules']}.")
    add("")
    pj, kj = kl["pointer_journey"], kl["keyboard_only_journey"]
    add(_table(["Journey", "K", "P", "B", "H", "M", "Standard total s", "Fitts-refined total s"], [
        ["Pointer + typing", *[pj["operator_counts"][k] for k in "KPBHM"], pj["total_s"], pj["fitts_refined_total_s"]],
        ["Keyboard only (Tab, Enter, Space, arrows)", *[kj["operator_counts"][k] for k in "KPBHM"], kj["total_s"], "-"]]))
    add("")
    add(f"Expected expert time is {pj['total_s']} s pointer-driven (Fitts-refined {pj['fitts_refined_total_s']} s) and {kj['total_s']} s keyboard-only, excluding system response "
        f"(measured wait, sum of per-step p50: {dh['journey_wait_p50_sum_s']} s) and scrolling.")
    add("")
    add(_table(["Step", "KLM s (pointer)", "Operators"], [[st["id"], pj["per_step_s"].get(st["id"], 0), _ops(pj["operators"], st["id"])] for st in rep["journey"]["steps"]]))
    add("")
    add("## Doherty threshold (measured; varies run to run)")
    add("")
    add(f"{dh['note']}. Percentiles are {dh['method']}; {dh['interactions_measured']} interactions. Native checkbox toggles that change no DOM "
        f"({', '.join(dh['native_control_interactions_excluded']) or 'none'}) are excluded.")
    add("")
    add(_table(["Step", "n", "First feedback p50 ms", "p95 ms", "Settled p50 ms", "p95 ms", "> 400 ms"],
               [[x["step"], x["samples"], x["first_feedback_p50_ms"], x["first_feedback_p95_ms"], x["settled_p50_ms"], x["settled_p95_ms"], ("p50" if x["median_over_400ms"] else "p95 only" if x["over_400ms"] else "ok")] for x in dh["steps"]]))
    add("")
    add(f"Overall: first feedback p50/p95 {dh['first_feedback_p50_ms']}/{dh['first_feedback_p95_ms']} ms; settled p50/p95 {dh['settled_p50_ms']}/{dh['settled_p95_ms']} ms "
        f"(max {dh['settled_max_ms']} ms). Keyboard activations settled p50/p95 {dh['keyboard_settled_p50_ms']}/{dh['keyboard_settled_p95_ms']} ms.")
    add("")
    add("## WCAG 2.2 AA")
    add("")
    add(f"{wc['engine']}. Views audited: {', '.join(wc['views_audited'])}.")
    add("")
    if wc["violations_by_rule"]:
        add(_table(["Rule", "Impact", "Nodes", "Views", "Help"], [[v["id"], v["impact"], v["node_count"], ", ".join(v["views"]), v["help"]] for v in wc["violations_by_rule"]]))
    else:
        add("No axe violations in the audited views.")
    add("")
    if wc["needs_review_rules"]:
        add("Needs manual review (axe `incomplete`): " + ", ".join(f"{x['id']} ({x['impact']})" for x in wc["needs_review_rules"]) + ".")
        add("")
    ts = wc["target_size_2_5_8"]
    add(f"Target size (own audit of {ts['controls_audited']} controls): {ts['status_counts']}. Exceptions not evaluated: {', '.join(ts['exceptions_not_evaluated'])}.")
    add("")
    if ts["undersized_or_failing"]:
        add(_table(["Control", "Status", "Effective px", "Raw px", "Via label"],
                   [[f"{x['name'][:40]} `{x['selector']}`", x["status"], "x".join(map(str, x["effective_px"])), "x".join(map(str, x["raw_px"])), x["via_label"]] for x in ts["undersized_or_failing"]]))
        add("")
    add(_table(["Viewport", "Tabs with horizontal overflow (WCAG 1.4.10)", "Targets failing 2.5.8"],
               [[k, ", ".join(v["horizontal_overflow_tabs"]) or "none", v["targets_fail_2_5_8"]] for k, v in wc["reflow_and_targets_by_viewport"].items()]))
    add("")
    so = wc["supplementary_state_only_visual"]
    add(f"Supplementary heuristic ({so['authority']}): {so['check']}: {', '.join(f'`{e}`' for e in so['elements']) or 'none'}.")
    add("")
    add("## Keyboard-only traversal")
    add("")
    add(f"The whole journey completed with the keyboard alone: {kb['tab_presses_total']} Tab presses; most for one target {kb['max_tab_presses_for_one_target']}; "
        f"{kb['unique_focus_stops_seen']} distinct focus stops seen; {kb['focus_lost_count']} of {kb['activations']} activations dropped focus to the page body "
        f"({', '.join(kb['activations_that_lost_focus']) or 'none'}); {kb['tab_presses_spent_after_focus_loss']} Tab presses were spent on steps right after a focus loss; "
        f"{len(kb['stops_without_visible_focus_indicator'])} stops without a visible indicator; {kb['focus_order_regression_count']} upward focus moves. {kb['note']}.")
    add("")
    add(_table(["Step", "Tab presses"], [[st["id"], kb["tab_presses_by_step"][st["id"]]] for st in rep["journey"]["steps"] if st["id"] in kb["tab_presses_by_step"]]))
    add("")
    add("## Working memory (heuristic proxy)")
    add("")
    add(f"{wm['label']}. {wm['definition']}. Citations: {'; '.join(wm['citations'])}.")
    add("")
    add(_table(["View", "Controls", "Content groups", "Chunks (viewport)", "Chunks (page)", "> 9"],
               [[v["view"], v["controls"], v["content_groups"], v["chunks_viewport"], v["chunks_page"], "FLAG" if v["over_miller_9"] else "ok"] for v in wm["views"]]))
    add("")
    add("## Runtime hygiene")
    add("")
    re_ = rep["runtime_errors"]
    add(f"JavaScript exceptions: {len(re_['javascript_exceptions'])}. HTTP error responses: "
        + ("; ".join(f"{x['status']} {x['method']} {x['path']} during `{x['step']}`" for x in re_["http_error_responses"]) or "none") + ".")
    add("")
    add("## Limitations")
    add("")
    out += [f"- {x}" for x in rep["limitations"]]
    add("")
    add("## NOT_RUN")
    add("")
    out += [f"- {x}" for x in rep["not_run"]]
    add("")
    return "\n".join(out)


def _ops(operators: list[dict], step: str) -> str:
    return " ".join(o["op"] for o in operators if o["step"] == step)


# --- publish / drift ---------------------------------------------------------------------------
def publish_docs(report: dict) -> None:
    """Commit-ready evidence: the JSON snapshot plus the Markdown rendered from it."""
    write_text(SNAPSHOT, dumps(report))
    write_text(REPORT_MD, render_markdown(report))


def check_docs() -> tuple[bool, str]:
    """Drift check: does REPORT.md equal render(snapshot)? Does the snapshot match the current UI bytes?

    The first is a hard requirement (a hand-edited or stale rendering). The second is informational:
    when the UI changes the snapshot is legitimately stale until `nox -s hci` is rerun."""
    if not SNAPSHOT.exists() or not REPORT_MD.exists():
        return False, "docs/hci/report.snapshot.json or REPORT.md missing; run `python -m quality.hci run --publish-docs`"
    snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    if REPORT_MD.read_bytes() != render_markdown(snapshot).encode("utf-8"):
        return False, "DRIFT: docs/hci/REPORT.md differs from render(report.snapshot.json)"
    from .journey import ui_hashes
    note = ""
    if snapshot["environment"]["ui_sha256"] != ui_hashes():
        note = " (informational: UI bytes changed since the snapshot; rerun `nox -s hci` to refresh evidence)"
    return True, "docs/hci/REPORT.md matches render(report.snapshot.json)" + note
